# Generated by Django 2.2.7 on 2019-11-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedIn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
