# Generated by Django 2.2.7 on 2019-11-26 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvmaker', '0002_auto_20191126_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='brief_description',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('currently_working_here', models.BooleanField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=300)),
                ('school_location', models.CharField(blank=True, max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('degree', models.CharField(max_length=500)),
                ('field_of_study', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('currently_attending_here', models.BooleanField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
