# Generated by Django 2.2.6 on 2019-10-07 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='no_of_semester',
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('credit_hour', models.FloatField()),
                ('code', models.CharField(max_length=10)),
                ('detail', models.CharField(max_length=300)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Semester')),
            ],
        ),
    ]
