# Generated by Django 2.2.7 on 2019-12-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snkr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('retailer_sku', models.IntegerField()),
                ('url', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Skus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField(max_length=200)),
                ('sku_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snkr_skus', to='snkr.Snkr')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=150)),
                ('image_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snkr_images', to='snkr.Snkr')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('product_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snkr_descriptions', to='snkr.Snkr')),
            ],
        ),
    ]
