# Generated by Django 2.2.6 on 2019-10-15 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4rth'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'UnderGraduate'), (2, 'Graduate'), (3, 'Phd')], default=1)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_programs', to='institutions.Campus')),
            ],
            options={
                'unique_together': {('name', 'campus')},
            },
        ),
        migrations.AddField(
            model_name='campus',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_campuses', to='institutions.Institution'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('credit_hour', models.FloatField()),
                ('code', models.CharField(max_length=10)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='institutions.Program')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_courses', to='institutions.Semester')),
            ],
            options={
                'unique_together': {('name', 'program')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='campus',
            unique_together={('name', 'institute')},
        ),
    ]
