# Generated by Django 2.2.6 on 2019-10-16 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='program_semesters', to='institutions.Program'),
        ),
    ]
