# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfacebook', '0003_auto_20171027_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='status_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to='myfacebook.UserProfile'),
        ),
    ]
