# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfacebook', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(),
        ),
    ]
