# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfacebook', '0011_auto_20171101_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
