# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfacebook', '0013_auto_20171101_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
    ]
