# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfacebook', '0015_auto_20171102_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowers',
            options={},
        ),
        migrations.AlterField(
            model_name='news',
            name='detail',
            field=models.TextField(max_length=3000),
        ),
    ]
