from .views import (
    AboutPageListView,
    add_google_lib_book,
    AllPublicNoteBookListView,
    AllPublicNoteListView,
    CreateNote,
    CreateNoteBook,
    DeleteNote,
    DeleteNoteBook,
    HomePageListView,
    NoteListView,
    NotePublicListView,
    NotePublicView,
    PublicHomePageListView,
    search_books,
    search_by_keywords,
    UpdateNote,
    UpdateNoteBook,
)
from django.urls import path

urlpatterns = [
    path('', PublicHomePageListView.as_view(), name='notes-public-page'),
    path('about/', AboutPageListView.as_view(), name='notes-about-page'),
    path('home/', HomePageListView.as_view(), name='notes-home-page'),
    path('note-book/<int:pk>/delete', DeleteNoteBook.as_view(), name='note-book-delete'),
    path('note-book/<int:pk>/notes', NoteListView.as_view(), name='note-book-notes'),
    path('note-book/<int:pk>/update', UpdateNoteBook.as_view(), name='note-book-update'),
    path('note-book/create', CreateNoteBook.as_view(), name='note-book-create'),
    path('note-book/find/results', search_by_keywords, name='search-notes'),
    path('note-book/note/<int:note_book>/create', CreateNote.as_view(), name='note-create'),
    path('note-book/note/<int:pk>/delete', DeleteNote.as_view(), name='note-delete'),
    path('note-book/note/<int:pk>/update', UpdateNote.as_view(), name='note-update'),
    path('note-book/note/<int:pk>/view', NotePublicView.as_view(), name='note-public-view'),
    path('note-book/notes/<int:pk>/view', NotePublicListView.as_view(), name='note-book-public-notes'),
    path('note-book/public-notes', AllPublicNoteListView.as_view(), name='all-public-notes'),
    path('note-book/search-books/add-book/', add_google_lib_book, name='add-book'),
    path('note-book/search-books/', search_books, name='search-books'),
    path('note-books/', AllPublicNoteBookListView.as_view(), name='all-public-note-books'),
]
