# Generated by Django 2.2.6 on 2019-10-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20191022_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Librarian',
            new_name='librarian',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
