# Generated by Django 2.2.6 on 2019-10-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20191022_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='librarian',
            new_name='user',
        ),
    ]
