# Generated by Django 2.2.6 on 2019-10-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_issuebook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuebook',
            options={'get_latest_by': 'issue_date', 'ordering': ['title'], 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
