# Generated by Django 2.2.6 on 2019-10-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20191024_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', unique=True),
        ),
    ]
