# Generated by Django 2.2.6 on 2019-10-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20191024_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
