# Generated by Django 2.2.6 on 2019-10-28 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBook',
            fields=[
                ('issuebook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.IssueBook')),
            ],
            options={
                'verbose_name': 'request_book',
                'verbose_name_plural': 'request_books',
                'ordering': ['title'],
                'get_latest_by': 'issue_date',
            },
            bases=('books.issuebook',),
        ),
    ]
