# Generated by Django 2.2.6 on 2019-10-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_requestbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestBook',
        ),
    ]
