# Generated by Django 2.2.6 on 2019-10-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20191028_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
