# Generated by Django 2.2.6 on 2019-10-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20191028_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='requestbook',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
