# Generated by Django 2.2.6 on 2019-10-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20191028_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestbook',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
