# Generated by Django 2.2.6 on 2019-10-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_auto_20191029_1013'),
    ]

    operations = [
    ]
