# Generated by Django 2.2.6 on 2019-10-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_auto_20191030_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
