# Generated by Django 2.2.6 on 2019-11-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_remove_book_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuebook',
            options={'get_latest_by': 'issue_date', 'ordering': ['book'], 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.AlterModelOptions(
            name='requestbook',
            options={'get_latest_by': 'issue_date', 'ordering': ['book'], 'verbose_name': 'book_request', 'verbose_name_plural': 'books_requests'},
        ),
        migrations.RemoveField(
            model_name='issuebook',
            name='title',
        ),
        migrations.RemoveField(
            model_name='requestbook',
            name='title',
        ),
    ]
