# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='Date completed')),
                ('status', models.CharField(choices=[('inprogress', 'In Progress'), ('complete', 'Complete'), ('pending', 'Pending')], default='pending', max_length=32)),
                ('log', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('is_manager', 'manager perms'),),
            },
        ),
    ]
