# Generated by Django 2.2.dev20180707212002 on 2018-07-23 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattingAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_format', models.CharField(default=' ', max_length=50)),
                ('matches', models.IntegerField()),
                ('innings', models.IntegerField()),
                ('not_outs', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('highest_score', models.CharField(default=' ', max_length=50)),
                ('average', models.FloatField(default=0)),
                ('balls_faced', models.IntegerField()),
                ('strike_rate', models.FloatField(default=0)),
                ('hundreds', models.IntegerField()),
                ('fifties', models.IntegerField(blank=True, null=True)),
                ('fours', models.IntegerField()),
                ('sixes', models.IntegerField()),
                ('catches', models.IntegerField()),
                ('stumps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BowlingAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_format', models.CharField(default=' ', max_length=50)),
                ('matches', models.IntegerField()),
                ('innings', models.IntegerField()),
                ('balls', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('best_bowling_innings', models.CharField(default=' ', max_length=50)),
                ('best_bowling_match', models.CharField(default=' ', max_length=50)),
                ('average', models.FloatField(default=0)),
                ('economy', models.FloatField(default=0)),
                ('strike_rate', models.FloatField(default=0)),
                ('four_wickets', models.IntegerField()),
                ('five_wickets', models.IntegerField()),
                ('ten_wickets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('born', models.DateTimeField(verbose_name='born')),
                ('playing_role', models.CharField(default=' ', max_length=50)),
                ('batting_style', models.CharField(default=' ', max_length=50)),
                ('bowling_style', models.CharField(default=' ', max_length=50)),
                ('major_team', models.CharField(default=' ', max_length=200)),
                ('ranking', models.IntegerField(default=0)),
                ('url', models.URLField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(default=' ', max_length=100)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('ranking', models.IntegerField(default=0)),
                ('type', models.CharField(default='county', max_length=20)),
                ('url', models.URLField(default=' ', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bowlingaverage',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Player'),
        ),
        migrations.AddField(
            model_name='battingaverage',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Player'),
        ),
    ]
