# Generated by Django 2.0.7 on 2018-07-30 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattingAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('format', models.CharField(choices=[('test', 'Test'), ('odi', 'ODI'), ('t20i', 'T20I'), ('firstclass', 'FirstClass'), ('lista', 'ListA'), ('t20s', 'T20s')], max_length=50)),
                ('matches', models.IntegerField(blank=True, null=True)),
                ('innings', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('strike_rate', models.FloatField(blank=True, null=True)),
                ('balls', models.IntegerField(blank=True, null=True)),
                ('not_outs', models.IntegerField(blank=True, null=True)),
                ('highest_score', models.CharField(default=' ', max_length=50)),
                ('hundreds', models.IntegerField(blank=True, null=True)),
                ('fifties', models.IntegerField(blank=True, null=True)),
                ('fours', models.IntegerField(blank=True, null=True)),
                ('sixes', models.IntegerField(blank=True, null=True)),
                ('catches', models.IntegerField(blank=True, null=True)),
                ('stumps', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BowlingAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('format', models.CharField(choices=[('test', 'Test'), ('odi', 'ODI'), ('t20i', 'T20I'), ('firstclass', 'FirstClass'), ('lista', 'ListA'), ('t20s', 'T20s')], max_length=50)),
                ('matches', models.IntegerField(blank=True, null=True)),
                ('innings', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('strike_rate', models.FloatField(blank=True, null=True)),
                ('balls', models.IntegerField(blank=True, null=True)),
                ('wickets', models.IntegerField(blank=True, null=True)),
                ('best_bowling_innings', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('best_bowling_match', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('economy', models.FloatField(blank=True, null=True)),
                ('four_wickets', models.IntegerField(blank=True, null=True)),
                ('five_wickets', models.IntegerField(blank=True, null=True)),
                ('ten_wickets', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('photo_url', models.URLField(default=' ', max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'articles'), ('model', 'article')), models.Q(('app_label', 'teams'), ('model', 'player')), models.Q(('app_label', 'teams'), ('model', 'team')), models.Q(('app_label', 'users'), ('model', 'profile')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(default=' ', max_length=100)),
                ('DOB', models.DateField(verbose_name='Born')),
                ('playing_role', models.CharField(choices=[('bat', 'Batsman'), ('bowl', 'Bowler'), ('all', 'AllRounder'), ('wkt', 'WicketKeeper')], default=' ', max_length=20)),
                ('batting_style', models.CharField(choices=[('rhb', 'Right Hand Bat'), ('lhb', 'Left Hand Bat')], default=' ', max_length=20)),
                ('bowling_style', models.CharField(choices=[('raf', 'Right Arm Fast'), ('ramf', 'Right Arm Medium Fast'), ('raob', 'Right Arm OffBreak'), ('ralg', 'Right Arm LegBreak Googly'), ('rao', 'Right Arm Orthodox'), ('laf', 'Left Arm Fast'), ('lamf', 'Left Arm Medium Fast'), ('lao', 'Left Arm Orthodox'), ('lac', 'Left Arm Chinaman')], default=' ', max_length=30)),
                ('ranking', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, default=' ', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(default=' ', max_length=50)),
                ('ranking', models.IntegerField(default=0)),
                ('type', models.CharField(default='county', max_length=20)),
                ('url', models.URLField(default=' ', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='players', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='bowlingaverage',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_average', to='teams.Player'),
        ),
        migrations.AddField(
            model_name='battingaverage',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_average', to='teams.Player'),
        ),
    ]
