# Generated by Django 2.2.dev20180707212002 on 2018-07-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerPhotos',
            new_name='Photos',
        ),
        migrations.RenameField(
            model_name='battingaverage',
            old_name='match_format',
            new_name='format',
        ),
        migrations.RenameField(
            model_name='bowlingaverage',
            old_name='match_format',
            new_name='format',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='born',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='major_team',
            new_name='major_teams',
        ),
        migrations.RemoveField(
            model_name='battingaverage',
            name='balls_faced',
        ),
        migrations.AddField(
            model_name='battingaverage',
            name='balls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battingaverage',
            name='average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='battingaverage',
            name='catches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battingaverage',
            name='fours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battingaverage',
            name='hundreds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battingaverage',
            name='innings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battingaverage',
            name='matches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battingaverage',
            name='not_outs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battingaverage',
            name='runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battingaverage',
            name='sixes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battingaverage',
            name='strike_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='battingaverage',
            name='stumps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='balls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='best_bowling_innings',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='best_bowling_match',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='economy',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='five_wickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='four_wickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='innings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='matches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='strike_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='ten_wickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='wickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='batting_style',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='bowling_style',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='playing_role',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='ranking',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
