# Generated by Django 2.0.7 on 2018-08-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_livescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingaverage',
            name='format',
            field=models.CharField(choices=[('TEST', 'Test'), ('ODI', 'ODI'), ('T20I', 'T20I'), ('FIRSTCLASS', 'FirstClass'), ('LISTA', 'ListA'), ('T20S', 'T20s')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='format',
            field=models.CharField(choices=[('TEST', 'Test'), ('ODI', 'ODI'), ('T20I', 'T20I'), ('FIRSTCLASS', 'FirstClass'), ('LISTA', 'ListA'), ('T20S', 'T20s')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='batting_style',
            field=models.CharField(choices=[('RIGHT_HANDED', 'Right Hand Bat'), ('LEFT_HANDED', 'Left Hand Bat')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='bowling_style',
            field=models.CharField(choices=[('RIGHT_ARM_FAST', 'Right Arm Fast'), ('RIGHT_ARM_MEDIUM_FAST', 'Right Arm Medium Fast'), ('RIGHT_ARM_OFF_BREAK', 'Right Arm OffBreak'), ('RIGHT_ARM_LEG_BREAK_GOOGLY', 'Right Arm LegBreak Googly'), ('RIGHT_ARM_ORTHODOX', 'Right Arm Orthodox'), ('LEFT_ARM_FAST', 'Left Arm Fast'), ('LEFT_ARM_MEDIUM_FAST', 'Left Arm Medium Fast'), ('LEFT_ARM_ORTHODOX', 'Left Arm Orthodox'), ('LEFT_ARM_CHINAMAN', 'Left Arm Chinaman')], default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='playing_role',
            field=models.CharField(choices=[('BATSMAN', 'Batsman'), ('BOWLER', 'Bowler'), ('ALLROUNDER', 'AllRounder'), ('WICKETKEEPER', 'WicketKeeper')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='type',
            field=models.CharField(choices=[('INTERNATIONAL', 'International'), ('COUNTY', 'County')], max_length=20),
        ),
    ]
