# Generated by Django 2.2.dev20180707212002 on 2018-07-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20180723_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingaverage',
            name='format',
            field=models.CharField(choices=[('test', 'Tests'), ('odi', 'ODIs'), ('t20i', 'T20Is'), ('first-class', 'FirstClass'), ('list A', 'ListA'), ('t20', 'T20s')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='format',
            field=models.CharField(choices=[('test', 'Tests'), ('odi', 'ODIs'), ('t20i', 'T20Is'), ('first-class', 'FirstClass'), ('list A', 'ListA'), ('t20', 'T20s')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='batting_style',
            field=models.CharField(choices=[('right-hand', 'Right Hand Bat'), ('left-hand', 'Left Hand Bat')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='bowling_style',
            field=models.CharField(choices=[('right-arm-fast', 'Right Arm Fast'), ('right-arm-medium-fast', 'Right Arm Medium Fast'), ('right-arm-off-break', 'Right Arm OffBreak'), ('right-arm-leg-break-googly', 'Right Arm LegBreak Googly'), ('right-arm-orthodox', 'Right Arm Orthodox'), ('left-arm-fast', 'Left Arm Fast'), ('left-arm-medium-fast', 'Left Arm Medium Fast'), ('left-arm-orthodox', 'Left Arm Orthodox'), ('left-arm-chinaman', 'Left Arm Chinaman')], default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='playing_role',
            field=models.CharField(choices=[('batsman', 'Batsman'), ('bowler', 'Bowler'), ('allrounder', 'AllRounder'), ('wicketkeeper', 'WicketKeeper')], default=' ', max_length=20),
        ),
    ]
