# Generated by Django 2.0.7 on 2018-08-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20180801_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='battingaverage',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_averages', to='teams.Player'),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_averages', to='teams.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='formats',
            field=models.ManyToManyField(blank=True, related_name='players', to='teams.Format'),
        ),
    ]
