# Generated by Django 2.2.dev20180707212002 on 2018-07-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20180723_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingaverage',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battingaverage',
            name='format',
            field=models.CharField(choices=[('test', 'test'), ('odi', 'odi'), ('t20i', 't20i'), ('firstclass', 'firstclass'), ('lista', 'lista'), ('t20s', 't20s')], max_length=50),
        ),
        migrations.AlterField(
            model_name='battingaverage',
            name='strike_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='economy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='format',
            field=models.CharField(choices=[('test', 'test'), ('odi', 'odi'), ('t20i', 't20i'), ('firstclass', 'firstclass'), ('lista', 'lista'), ('t20s', 't20s')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='strike_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='batting_style',
            field=models.CharField(choices=[('rhb', 'Right Hand Bat'), ('lhb', 'Left Hand Bat')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='bowling_style',
            field=models.CharField(choices=[('raf', 'Right Arm Fast'), ('ramf', 'Right Arm Medium Fast'), ('raob', 'Right Arm OffBreak'), ('ralg', 'Right Arm LegBreak Googly'), ('rao', 'Right Arm Orthodox'), ('laf', 'Left Arm Fast'), ('lamf', 'Left Arm Medium Fast'), ('lao', 'Left Arm Orthodox'), ('lac', 'Left Arm Chinaman')], default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='playing_role',
            field=models.CharField(choices=[('bat', 'Batsman'), ('bowl', 'Bowler'), ('all', 'AllRounder'), ('wkt', 'WicketKeeper')], default=' ', max_length=20),
        ),
    ]
