# Generated by Django 2.0.7 on 2018-08-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20180802_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingaverage',
            name='format',
            field=models.CharField(blank=True, choices=[('TESTS', 'Test'), ('ODIS', 'ODI'), ('T20IS', 'T20I'), ('FIRST-CLASS', 'FirstClass'), ('LIST A', 'ListA'), ('T20S', 'T20s')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='battingaverage',
            name='highest_score',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='format',
            field=models.CharField(blank=True, choices=[('TESTS', 'Test'), ('ODIS', 'ODI'), ('T20IS', 'T20I'), ('FIRST-CLASS', 'FirstClass'), ('LIST A', 'ListA'), ('T20S', 'T20s')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='bowling_style',
            field=models.CharField(choices=[('RIGHT_ARM_FAST', 'Right Arm Fast'), ('RIGHT_ARM_MEDIUM_FAST', 'Right Arm Medium Fast'), ('RIGHT_ARM_OFF_BREAK', 'Right Arm OffBreak'), ('RIGHT_ARM_LEG_BREAK_GOOGLY', 'Right Arm LegBreak Googly'), ('RIGHT_ARM_ORTHODOX', 'Right Arm Orthodox'), ('RIGHT_ARM_SLOW', 'Right Arm Slow'), ('LEFT_ARM_FAST', 'Left Arm Fast'), ('LEFT_ARM_MEDIUM_FAST', 'Left Arm Medium Fast'), ('LEFT_ARM_ORTHODOX', 'Left Arm Orthodox'), ('LEFT_ARM_CHINAMAN', 'Left Arm Chinaman'), ('LEFT_ARM_SLOW', 'Left Arm Slow')], default=' ', max_length=30),
        ),
    ]
