# Generated by Django 2.0.7 on 2018-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20180723_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingaverage',
            name='format',
            field=models.CharField(choices=[('test', 'Test'), ('odi', 'ODI'), ('t20i', 'T20I'), ('firstclass', 'FirstClass'), ('lista', 'ListA'), ('t20s', 'T20s')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='format',
            field=models.CharField(choices=[('test', 'Test'), ('odi', 'ODI'), ('t20i', 'T20I'), ('firstclass', 'FirstClass'), ('lista', 'ListA'), ('t20s', 'T20s')], max_length=50),
        ),
    ]
