# Generated by Django 2.0.7 on 2018-07-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_testmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='deleted',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
