# Generated by Django 2.0.7 on 2018-07-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20180726_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='photo',
            field=models.ImageField(default='/home/raziullah/DjangoCricketApp/the-lab/static/media/generic.png', upload_to='media/%Y/%m/%d'),
        ),
    ]
