# Generated by Django 2.0.7 on 2018-07-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_photos_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
