# Generated by Django 2.0.7 on 2018-07-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20180727_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingaverage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bowlingaverage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='/home/raziullah/DjangoCricketApp/the-lab/static/media/generic.png', upload_to='media'),
        ),
    ]
