# Generated by Django 2.0.7 on 2018-07-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20180727_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingaverage',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_average', to='teams.Player'),
        ),
        migrations.AlterField(
            model_name='bowlingaverage',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_average', to='teams.Player'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='teams.Player'),
        ),
    ]
