# Generated by Django 2.0.7 on 2018-07-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20180727_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerteam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
