# Generated by Django 2.0.7 on 2018-07-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('teams', '0014_playerteam_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerteam',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerteam',
            name='team',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.RemoveField(
            model_name='testphoto',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='player',
        ),
        migrations.AddField(
            model_name='photo',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(related_name='players', to='teams.Team'),
        ),
        migrations.DeleteModel(
            name='PlayerTeam',
        ),
        migrations.DeleteModel(
            name='TestPhoto',
        ),
    ]
