# Generated by Django 2.0.7 on 2018-07-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_player_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='major_teams',
        ),
    ]
