# Generated by Django 2.0.7 on 2018-07-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_remove_player_major_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='players', to='teams.Team'),
        ),
    ]
