# Generated by Django 2.0.7 on 2018-07-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_auto_20180727_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='DOB',
            field=models.DateField(verbose_name='Born'),
        ),
    ]
