# Generated by Django 2.0.7 on 2018-07-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_auto_20180727_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
