# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20170908_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
