# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_remove_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('public', 'public'), ('friends', 'friends'), ('only_me', 'only_me')], default='public', max_length=10),
        ),
    ]
