import scrapy


class Item(scrapy.Item):
    observation_date = scrapy.Field()
    observation_time = scrapy.Field()
    POS = scrapy.Field()
    oneway_indicator = scrapy.Field()
    origin = scrapy.Field()
    destination = scrapy.Field()
    outbound_travel_stopover = scrapy.Field()
    outbound_travel_duration = scrapy.Field()
    inbound_travel_stopover = scrapy.Field()
    inbound_travel_duration = scrapy.Field()
    carrier = scrapy.Field()
    outbound_flight_number = scrapy.Field()
    inbound_flight_number = scrapy.Field()
    site_source = scrapy.Field()
    source = scrapy.Field()
    outbound_departure_date = scrapy.Field()
    outbound_arrival_date = scrapy.Field()
    inbound_arrival_date = scrapy.Field()
    inbound_departure_date = scrapy.Field()
    outbound_fare_basis = scrapy.Field()
    inbound_fare_basis = scrapy.Field()
    outbound_booking_class = scrapy.Field()
    inbound_booking_class = scrapy.Field()
    outbound_bundle = scrapy.Field()
    inbound_bundle = scrapy.Field()
    price_exc = scrapy.Field()
    price_inc = scrapy.Field()
    tax = scrapy.Field()
    currency = scrapy.Field()
    price_outbound = scrapy.Field()
    price_inbound = scrapy.Field()
    is_tax_inc_outin = scrapy.Field()
    OD = scrapy.Field()
