# Generated by Django 2.2.3 on 2019-09-04 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_friend', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('friend', 'friend'), ('group', 'group')], max_length=20)),
                ('url_accept', models.CharField(max_length=50)),
                ('url_cancel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SocialGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.SocialGroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('address', models.TextField()),
                ('friends', models.ManyToManyField(related_name='_userprofile_friends_+', through='user_management.Friend', to='user_management.UserProfile')),
                ('social_groups', models.ManyToManyField(blank=True, default=django.db.models.deletion.SET_NULL, through='user_management.UserGroup', to='user_management.SocialGroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('job_location', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=30)),
                ('joining_date', models.DateField(auto_now=True)),
                ('leaving_date', models.DateField(default='')),
                ('status', models.BooleanField(default=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='usergroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.UserProfile'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='user_management.UserProfile'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='user_management.UserProfile'),
        ),
        migrations.CreateModel(
            name='AcademicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(choices=[('School', 'School'), ('College', 'College'), ('University', 'University')], error_messages={'invalid_choice ': 'Invalid choice of academic institution'}, max_length=20)),
                ('institution_name', models.CharField(max_length=50)),
                ('degree_type', models.CharField(choices=[('Under Graduate', 'Under Graduate'), ('Post Graduate', 'Post Graduate')], error_messages={'invalid_choice': 'Invalid choice of degree type'}, max_length=20)),
                ('start_date', models.DateField(default='')),
                ('end_date', models.DateField(default='')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.UserProfile')),
            ],
        ),
    ]
