# Generated by Django 2.2.3 on 2019-09-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend', 'Friend'), ('group', 'Group')], max_length=20),
        ),
    ]
