

class Configurations:

    TIME_INTERVAL = 1
    CHANGE_IN_SPEED = 1
    SLEEPING_INTERVAL = 1
    RIDE_MOVING_FARE_COST = 3
    RIDE_WAITING_FARE_COST = 1
    RIDE_MOVING_STATE = 'MOVING'
    RIDE_PAUSE_STATE = 'PAUSE'
    RIDE_END_STATE = 'END'


