# Generated by Django 2.2.6 on 2019-10-30 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191029_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved')], default='Not Approved', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator(message='Format should be 1234-1234567', regex='^[\\d]{4}-[\\d]{7}$')]),
        ),
    ]
