# Generated by Django 2.2.6 on 2019-10-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191031_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='order_items', through='users.OrderItems', to='users.Product'),
        ),
    ]
