# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('completion_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=200)),
                ('assignments', models.ManyToManyField(to='training.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=200)),
                ('assignments', models.ManyToManyField(to='training.Assignment')),
                ('trainees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Trainee')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='technology_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Technology'),
        ),
    ]
