# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='trainees',
            new_name='trainee',
        ),
    ]
