# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20170621_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='picture',
            field=models.ImageField(max_length=200, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(max_length=200, upload_to=b''),
        ),
    ]
