# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20170623_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='picture',
            field=models.ImageField(max_length=200, upload_to='trainee_images/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(max_length=200, upload_to='trainer_images/'),
        ),
    ]
