# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20170630_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='picture',
            field=models.ImageField(default='default.png', max_length=200, upload_to='trainee_images/'),
        ),
    ]
