# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20170630_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(default='default.png', max_length=200, upload_to='trainer_images/'),
        ),
    ]
