# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0007_auto_20170630_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(default='default.png', max_length=200, upload_to='trainee_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='trainee',
        ),
        migrations.AddField(
            model_name='trainee',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.Trainer'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.UserProfile'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.UserProfile'),
        ),
    ]
