# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_remove_trainee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.UserProfile'),
        ),
    ]
