# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_auto_20170706_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='default.png', max_length=200, upload_to='user_images/'),
        ),
    ]
