# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_auto_20170707_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='assignments',
            field=models.ManyToManyField(null=True, to='training.Assignment'),
        ),
    ]
