# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_auto_20170707_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='technology_used',
        ),
        migrations.AddField(
            model_name='assignment',
            name='technology_used',
            field=models.ManyToManyField(to='training.Technology'),
        ),
    ]
