# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_auto_20170712_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateTime',
        ),
    ]
