# Generated by Django 2.2.dev20180707212002 on 2018-07-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('author', models.CharField(default='Author', max_length=50)),
                ('description', models.CharField(default='Description', max_length=100)),
                ('url', models.URLField(default=' ', max_length=100)),
            ],
        ),
    ]
