# Generated by Django 2.0.7 on 2018-07-30 09:10

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=100)),
                ('author', models.CharField(default=' ', max_length=50)),
                ('description', models.CharField(default=' ', max_length=100)),
                ('url', models.URLField(default=' ', max_length=100)),
                ('content', tinymce.models.HTMLField(default='')),
            ],
        ),
    ]
