# Generated by Django 2.0.7 on 2018-07-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='articles', to='teams.Player'),
        ),
        migrations.AddField(
            model_name='article',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='articles', to='teams.Team'),
        ),
    ]
