# Generated by Django 2.0.7 on 2018-07-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20180727_1131'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='teams.Player'),
        ),
        migrations.AddField(
            model_name='article',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
