# Generated by Django 2.0.7 on 2018-07-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180730_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('article', 'Article')], default=' ', max_length=10),
        ),
    ]
