# Generated by Django 2.0.7 on 2018-07-27 14:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_auto_20180727_1356'),
        ('articles', '0003_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='player',
        ),
        migrations.RemoveField(
            model_name='article',
            name='team',
        ),
        migrations.AddField(
            model_name='article',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='articles', to='teams.Player'),
        ),
        migrations.AddField(
            model_name='article',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='articles', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
