# Generated by Django 2.0.7 on 2018-08-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('ARTICLE', 'Article')], default=' ', max_length=10),
        ),
    ]
