export const LOGIN_ACTION = 'LOGI_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNUP_ACTION = 'SIGN_UP';
export const DISPLAY_SIGUP_TAB = 'DISPLAY_SIGNUP';
export const DISPLAY_LOGIN_TAB = 'DISPLAY_LOGIN';
export const GET_USERS_MEMS = 'GET_USERS_MEMS';
export const GET_PUBLIC_MEMS = 'GET_PUBLIC_MEMS';
export const GET_USER_ACTIVITIES = 'GET_USER_ACTIVITIES';
export const LOGOUT_ACTION = 'LOGOUT';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ADD_MEM = 'ADD_MEM';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const DELETE_MEM = 'DELETE_MEM';
export const GET_MEM = 'GET_MEM';

export const API_LOGIN_URL = 'http://localhost:8000/login/'; //Use with POST request method
export const API_LOGOUT_URL = 'http://localhost:8000/logout/';  //Use with POST request method
export const API_SIGNUP_URL = 'http://localhost:8000/signup/';  //Use with POST request method
export const API_USERS_MEMS_URL = 'http://localhost:8000/get-user-mems/' ; //USE with GET request method
export const API_PUBLIC_MEMS_URL = 'http://localhost:8000/get-public-mems/' ; //USE with GET request method
export const API_USER_ACTIVITIES_URL = 'http://localhost:8000/activities/' ; //USE with GET request method
export const API_USER_PROFILE_URL = 'http://localhost:8000/user/' ; //USE with GET request method [append user id]
export const API_ADD_CATEGORY_URL = 'http://localhost:8000/categories/' ; //USE with POST request method
export const API_GET_CATEGORIES_URL = 'http://localhost:8000/categories/' ; //USE with GET request method
export const API_MEMS_URL = 'http://localhost:8000/mems/' ; //USE with GET/POST/DELETE/PUT request method