# Generated by Django 2.2.4 on 2019-08-23 11:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('retailer_sku', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=700), size=None)),
                ('care', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=700), size=None)),
                ('image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
                ('market', models.CharField(max_length=10)),
                ('retailer', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
    ]
