# Generated by Django 2.2.4 on 2019-08-26 07:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_skus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None),
        ),
    ]
