# Generated by Django 2.2.4 on 2019-08-29 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190826_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='skus',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='products.Category'),
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
