# Generated by Django 2.2.4 on 2019-08-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190829_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.CharField(max_length=5),
        ),
    ]
