# Generated by Django 2.2.4 on 2019-08-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190829_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.CharField(max_length=15),
        ),
    ]
