# Generated by Django 2.2.4 on 2019-08-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190829_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='market',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='retailer_sku',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.CharField(max_length=20),
        ),
    ]
