# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:48
from __future__ import unicode_literals

import address.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('users', '0003_auto_20170710_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='address.Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'.", regex='^\\+?\\d{10,15}$')]),
        ),
    ]
