# Generated by Django 2.1.1 on 2018-09-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('custom_user', '0002_auto_20180907_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(default='2018-09-13 07:07:03.280381'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={
                'max_length': 'email should be of maximum length of 255.'}, max_length=255,
                                    verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, error_messages={
                'max_length': 'first name should be of maximum length of 40.'}, max_length=40,
                                   verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, error_messages={
                'max_length': 'last name should be of maximum length of 40.'}, max_length=40,
                                   verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(
                error_messages={'max_length': 'username should be of maximum length of 150.',
                                'required': 'Username is required',
                                'unique': 'A user with that username already exists.'},
                max_length=150, unique=True),
        ),
    ]
