# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_temp', models.FloatField(blank=True, default=0, null=True)),
                ('mean_temp', models.FloatField(blank=True, default=0, null=True)),
                ('min_temp', models.FloatField(blank=True, default=0, null=True)),
                ('max_dew', models.FloatField(blank=True, default=0, null=True)),
                ('mean_dew', models.FloatField(blank=True, default=0, null=True)),
                ('min_dew', models.FloatField(blank=True, default=0, null=True)),
                ('max_humidity', models.FloatField(blank=True, default=0, null=True)),
                ('mean_humidity', models.FloatField(blank=True, default=0, null=True)),
                ('min_humidity', models.FloatField(blank=True, default=0, null=True)),
                ('max_sea_pressure', models.FloatField(blank=True, default=0, null=True)),
                ('mean_sea_pressure', models.FloatField(blank=True, default=0, null=True)),
                ('min_sea_pressure', models.FloatField(blank=True, default=0, null=True)),
                ('max_visibility', models.FloatField(blank=True, default=0, null=True)),
                ('mean_visibility', models.FloatField(blank=True, default=0, null=True)),
                ('min_visibility', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
