# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinescore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
