# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinescore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='website_base_url',
            new_name='provider_website',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='website_url',
            new_name='target_url',
        ),
    ]
