# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinescore', '0002_auto_20170801_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(related_name='category', to='cinescore.Category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_of_release',
            field=models.CharField(max_length=12),
        ),
    ]
