# Generated by Django 2.2.7 on 2019-11-27 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0002_author_book_category_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='company_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
