BOT_NAME = 'ThermoFisher'

SPIDER_MODULES = ['ThermoFisher.spiders']
NEWSPIDER_MODULE = 'ThermoFisher.spiders'


ROBOTSTXT_OBEY = False

DOWNLOAD_DELAY = 2.0

AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 2
AUTOTHROTTLE_MAX_DELAY = 10
AUTOTHROTTLE_TARGET_CONCURRENCY = 15
