# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_store', '0003_auto_20170717_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='super_store.Product'),
        ),
    ]
