# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_auto_20170908_0749'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Added'), (2, 'Watched'), (3, 'Rated'), (4, 'Voted Actor'), (5, 'Recommended')])),
            ],
        ),
        migrations.CreateModel(
            name='WatchListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.BooleanField(default=False)),
                ('is_watched', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Like'), (2, 'Disliked')], null=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('best_actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Role')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlists.WatchListItem'),
        ),
    ]
