# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='movies.Movie'),
        ),
    ]
