# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0002_auto_20170911_0742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at']},
        ),
    ]
