# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0003_auto_20170911_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='best_actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='movies.Role'),
        ),
    ]
