# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0004_auto_20170912_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
