# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0005_watchlistitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Liked'), (2, 'Disliked')], null=True),
        ),
    ]
