export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const CLEAR_REGISTER_STATUS = "CLEAR_REGISTER_STATUS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

export const CREATE_POST = "CREATE_POST";
export const DELETE_POST = "DELETE_POST";
export const FETCH_FEED = "FETCH_FEED";
export const FETCH_USER_POSTS = "FETCH_USER_POSTS";

export const FETCH_USER = "FETCH_USER";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";

export const FETCH_FRIENDS = "FETCH_FRIENDS";
export const ADD_FRIEND = "ADD_FRIEND";
export const REMOVE_FRIEND = "REMOVE_FRIEND";

export const CREATE_COMMENT = "CREATE_COMMENT";
export const FETCH_COMMENTS = "FETCH_COMMENTS";

export const ADD_MEDIA = "ADD_MEDIA";
export const REMOVE_MEDIA = "REMOVE_MEDIA";
export const CLEAR_MEDIA = "CLEAR_MEDIA";
