// Publisher Actions
const PUBLISHER = {
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",

  FETCH_PUBLISHER_STARTED: "FETCH_PUBLISHER_STARTED",
  FETCH_PUBLISHER_SUCCESS: "FETCH_PUBLISHER_SUCCESS",
  FETCH_PUBLISHER_FAILURE: "FETCH_PUBLISHER_FAILURE",

  FETCH_PUBLISHERS_STARTED: "FETCH_PUBLISHERS_STARTED",
  FETCH_PUBLISHERS_SUCCESS: "FETCH_PUBLISHERS_SUCCESS",
  FETCH_PUBLISHERS_FAILURE: "FETCH_PUBLISHERS_FAILURE",

  FETCH_PUBLISHERS_DATA_STARTED: "FETCH_PUBLISHERS_DATA_STARTED",
  FETCH_PUBLISHERS_DATA_SUCCESS: "FETCH_PUBLISHERS_DATA_SUCCESS",
  FETCH_PUBLISHERS_DATA_FAILURE: "FETCH_PUBLISHERS_DATA_FAILURE",

  UPDATE_PUBLISHER_STARTED: "UPDATE_PUBLISHER_STARTED",
  UPDATE_PUBLISHER_SUCCESS: "UPDATE_PUBLISHER_SUCCESS",
  UPDATE_PUBLISHER_FAILURE: "UPDATE_PUBLISHER_FAILURE",

  DELETE_PUBLISHER_STARTED: "DELETE_PUBLISHER_STARTED",
  DELETE_PUBLISHER_SUCCESS: "DELETE_PUBLISHER_SUCCESS",
  DELETE_PUBLISHER_FAILURE: "DELETE_PUBLISHER_FAILURE"
}

export default PUBLISHER
