# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='size_of_page',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
