# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_crawler', '0002_webpage_size_of_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
