# Generated by Django 2.2.dev20180707212002 on 2018-07-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('ranking', models.IntegerField(default=0)),
                ('type', models.CharField(default='county', max_length=20)),
                ('url', models.URLField(default=' ', max_length=100)),
            ],
        ),
    ]
