"""These constants define what operation is to be performed"""
YEARLY_HIGHEST_LOWEST_TEMP_HUMID = 1
AVERAGE_TEMPERATURE = 2
TWO_LINE_CHART = 3
ONE_LINE_CHART = 4

"""These constants are for file column indices"""
MAX_TEMPERATURE_INDEX = 1
MIN_TEMPERATURE_INDEX = 3
MAX_HUMIDITY_INDEX = 7
MEAN_TEMPERATURE_INDEX = 2
MEAN_HUMIDITY_INDEX = 8
PKT_INDEX = 0

"""Color codes"""
COLOR_BLUE = '\033[1;34m'
COLOR_RED = '\033[1;31m'
COLOR_RESET = '\033[1;0m'
