# Constant module

EVENTS = ' Events'
MEAN_WIND_SPEED_KM_H = ' Mean Wind SpeedKm/h'
MAX_WIND_SPEED_KM_H = ' Max Wind SpeedKm/h'
MEAN_SEA_LEVEL_PRESSUREH_PA = ' Mean Sea Level PressurehPa'
MAX_SEA_LEVEL_PRESUUREH_PA = ' Max Sea Level PressurehPa'
MIN_SEA_LEVEL_PRESUUREH_PA = ' Min Sea Level PressurehPa'
MIN_TEMPERATURE_C = 'Min TemperatureC'
MAX_TEMPERATURE_C = 'Max TemperatureC'
MEAN_HUMIDITY = ' Mean Humidity'
MIN_HUMIDITY = ' Min Humidity'
MAX_HUMIDITY = 'Max Humidity'
MEAN_TEMPERATURE_C = 'Mean TemperatureC'
PKT = 'PKT'
WIND_DIR_DEGREES = 'WindDirDegrees'
MAX_VISIBILITY_KM = ' Max VisibilityKm'
MEAN_VISIBILITY_KM = ' Mean VisibilityKm'
MIN_VISIBILITY_KM = ' Min VisibilitykM'
MAX_GUST_SPEED_KM_H = ' Max Gust SpeedKm/h'
PRECIPITATION_MM = 'Precipitationmm'
DEW_POINT_C = 'Dew PointC'
MEAN_DEW_POINT_C = 'MeanDew PointC'
MIN_DUE_POINT_C = 'Min DewpointC'
CLOUD_COVER = ' CloudCover'
YEAR = "year"
MONTH = "month"
MONTHCHART = "monthchart"
BONUS_MONTHCHART = "bonuschart"
