# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20170714_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='assignments',
            field=models.ManyToManyField(to='training.Assignment'),
        ),
    ]
