class BaseClass:
    cities = ["Aachen", "Amberg (Bayern)", "Amberg (Bayern)", "Ansbach", "Aschaffenburg", "Augsburg",
              "Baden-Baden",
              "Bamberg", "Bayreuth", "Berlin", "Bielefeld", "Bochum", "Bonn", "Bottrop",
              "Brandenburg an der Havel",
              "Brandenburg an der Havel", "Brandenburg an der Havel", "Brandenburg an der Havel", "Braunschweig",
              "Bremen", "Bremerhaven", "Chemnitz", "Coburg", "Cottbus", "Darmstadt", "Delmenhorst",
              "Dessau-Ro\u00dflau", "Dessau-Ro\u00dflau", "Dortmund", "Dresden", "Duisburg", "D\u00fcsseldorf",
              "Eisenach (Th\u00fcringen)", "Eisenach (Th\u00fcringen)", "Emden (Niedersachsen)",
              "Emden (Niedersachsen)", "Erfurt", "Erlangen", "Essen", "Flensburg", "Frankenthal (Pfalz)",
              "Frankenthal (Pfalz)", "Frankfurt (Oder)", "Frankfurt (Oder)", "Frankfurt am Main",
              "Frankfurt am Main",
              "Frankfurt am Main", "Freiburg im Breisgau", "Freiburg im Breisgau", "Freiburg im Breisgau",
              "F\u00fcrth (Bayern)", "F\u00fcrth (Bayern)", "Gelsenkirchen", "Gera", "Greifswald", "G\u00f6rlitz",
              "Hagen (Nordrhein-Westfalen)", "Hagen (Nordrhein-Westfalen)", "Hagen (Nordrhein-Westfalen)",
              "Halle (Saale)", "Halle (Saale)", "Hamburg", "Hamm (Nordrhein-Westfalen)",
              "Hamm (Nordrhein-Westfalen)",
              "Hamm (Nordrhein-Westfalen)", "Hannover", "Heidelberg", "Heilbronn", "Herne", "Hof (Bayern)",
              "Hof (Bayern)", "Hoyerswerda", "Ingolstadt", "Jena", "Kaiserslautern", "Karlsruhe", "Kassel",
              "Kaufbeuren", "Kempten (Allg\u00e4u)", "Kempten (Allg\u00e4u)", "Kiel", "Koblenz", "Krefeld",
              "K\u00f6ln",
              "Landau in der Pfalz", "Landau in der Pfalz", "Landau in der Pfalz", "Landau in der Pfalz",
              "Landshut",
              "Leipzig", "Leverkusen", "Ludwigshafen am Rhein", "Ludwigshafen am Rhein", "Ludwigshafen am Rhein",
              "L\u00fcbeck", "Magdeburg", "Mainz", "Mannheim", "Memmingen", "M\u00f6nchengladbach",
              "M\u00fclheim an der Ruhr", "M\u00fclheim an der Ruhr", "M\u00fclheim an der Ruhr",
              "M\u00fclheim an der Ruhr", "M\u00fcnchen", "M\u00fcnster (Nordrhein-Westfalen)",
              "M\u00fcnster (Nordrhein-Westfalen)", "M\u00fcnster (Nordrhein-Westfalen)", "Neubrandenburg",
              "Neum\u00fcnster", "Neustadt an der Weinstra\u00dfe", "Neustadt an der Weinstra\u00dfe",
              "Neustadt an der Weinstra\u00dfe", "Neustadt an der Weinstra\u00dfe", "N\u00fcrnberg",
              "Oberhausen (Nordrhein-Westfalen)", "Oberhausen (Nordrhein-Westfalen)",
              "Oberhausen (Nordrhein-Westfalen)", "Offenbach am Main", "Offenbach am Main", "Offenbach am Main",
              "Oldenburg (Oldenburg)", "Osnabr\u00fcck", "Passau", "Pforzheim", "Pirmasens", "Plauen", "Potsdam",
              "Regensburg", "Remscheid", "Rosenheim", "Rostock", "Salzgitter", "Schwabach", "Schweinfurt",
              "Schwerin (Mecklenburg-Vorpommern)", "Schwerin (Mecklenburg-Vorpommern)",
              "Schwerin (Mecklenburg-Vorpommern)", "Solingen", "Speyer", "Stralsund", "Straubing", "Stuttgart",
              "Suhl",
              "Trier", "Ulm", "Weiden in der Oberpfalz", "Weiden in der Oberpfalz", "Weiden in der Oberpfalz",
              "Weiden in der Oberpfalz", "Weimar", "Wiesbaden", "Wilhelmshaven", "Wismar", "Wolfsburg", "Worms",
              "Wuppertal", "W\u00fcrzburg", "Zweibr\u00fccken", "Zwickau"]

    rent_types = [
        "APARTMENT_RENT",
        "HOUSE_RENT",
        "SHORT_TERM_ACCOMMODATION",
        "FLAT_SHARE_ROOM",
        "OFFICE_RENT",
        "INDUSTRY_RENT",
        "STORE_RENT",
        "GASTRONOMY_RENT",
        "SPECIAL_PURPOSE_RENT",
        "LIVING_RENT_SITE",
        "TRADE_SITE_RENT",
        "GARAGE_RENT",
        "ASSISTED_LIVING",
        "SENIOR_CARE"
    ]
    sale_types = [
        "APARTMENT_BUY",
        "HOUSE_BUY",
        "OFFICE_BUY",
        "INDUSTRY_BUY",
        "STORE_BUY",
        "GASTRONOMY_BUY",
        "SPECIAL_PURPOSE_BUY",
        "LIVING_BUY_SITE",
        "TRADE_SITE_BUY",
        "GARAGE_BUY",
        "INVESTMENT",
        "COMPULSORY_AUCTION",
        "HOUSE_TYPE"

    ]
