export const types = {
  AUTH_USER_STARTED: "AUTH_USER_STARTED",
  AUTH_USER_SUCCESS: "AUTH_USER_SUCCESS",
  AUTH_USER_FAILURE: "AUTH_USER_FAILURE",
  UPDATE_FORM: "UPDATE_FORM",
  LOGOUT_USER: "LOGOUT_USER",

};
