# Generated by Django 2.0.1 on 2018-01-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techlancers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
    ]
