# Generated by Django 2.0.1 on 2018-01-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techlancers', '0002_remove_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
