# Generated by Django 2.0.1 on 2018-01-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techlancers', '0003_auto_20180124_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
