# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20170630_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
