# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_auto_20170630_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
