# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_auto_20170630_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address1',
            new_name='current_address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='address2',
            new_name='permanent_address',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
    ]
