# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date of Birth'),
        ),
    ]
