# Generated by Django 2.1.1 on 2018-09-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_issue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(default='todo', max_length=20),
        ),
    ]
