# Generated by Django 2.1.1 on 2018-09-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_auto_20180928_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
