# Generated by Django 2.1.2 on 2018-10-15 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0009_auto_20180928_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='last_edit',
            new_name='edited_at',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='issue_id',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='last_edit',
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='issue.Issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='manage_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('high', 'high'), ('normal', 'normal'), ('low', 'low')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('review', 'review'), ('resolved', 'resolved')], default='todo', max_length=20),
        ),
    ]
