# Generated by Django 2.1.2 on 2018-10-15 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0011_auto_20181015_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='manage_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
