# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0005_auto_20170704_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.png', height_field='height_field', upload_to='profile_picture', width_field='width_field'),
        ),
    ]
