# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0007_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskS',
            new_name='Task',
        ),
    ]
