# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0008_auto_20170705_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dated',
            field=models.DateField(verbose_name='%m/%d/%Y'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
