# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0009_auto_20170705_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dated',
            field=models.DateField(),
        ),
    ]
