# Generated by Django 2.2.6 on 2019-10-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='author_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='isbn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='published_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='publisher_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
