# Generated by Django 2.2.6 on 2019-10-24 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20191024_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='published_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
