# Generated by Django 2.2.6 on 2019-10-28 12:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_auto_20191028_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
