# Generated by Django 2.2.6 on 2019-11-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_auto_20191028_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='thumbnail_url',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
