# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-08 12:28
from __future__ import unicode_literals
from django.db import migrations

from payroll_extra_fields.utils import OdooEmployee, OdooPayslip


def bulk_create_payslips(apps, schema_editor):
    import pdb; pdb.set_trace()
    employees = OdooEmployee.filter(limit=10)

    payslip_data = {
        "company_id": 1,
        "contract_id": 606,
        "description": "sample description text",
        "credit_note": False,
        "date_from": "2019-02-01",
        "date_to": "2019-02-28",
        "note": False,
        "number": False,
        "payslip_run_id": False,
        "struct_id": 2,
        "worked_days_line_ids": [
            [0, 5, {
                "code": "WORK100",
                "contract_id": 606,
                "name": "Normal Working Days paid at 100%",
                "number_of_days": 1,
                "number_of_hours": 8,
                "sequence": 1
            }]
        ],
        "line_ids": [
            [0, 7, {
                "amount": 990,
                "category_id": 4,
                "code": "LN",
                "name": "Loan",
                "quantity": 1,
                "rate": 100,
                "salary_rule_id": 12,
                "sequence": 5
            }], [0, 7, {
                "amount": 177,
                "category_id": 2,
                "code": "Bonus",
                "name": "Bonus",
                "quantity": 1,
                "rate": 100,
                "salary_rule_id": 13,
                "sequence": 5
            }]
        ]
    }

    for employee in employees:
        data = dict(payslip_data)
        data['employee_id'] = employee['id']
        data['name'] = 'Salary slip of {}'.format(employee['name'])

        OdooPayslip.create(data=data)


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_extra_fields', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(bulk_create_payslips)
    ]
