# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('text', models.TextField()),
                ('summary', models.TextField()),
                ('created_on', models.DateField(default=django.utils.timezone.localdate)),
                ('is_published', models.BooleanField(default=True)),
                ('comments_allowed', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('published_date', models.DateField(blank=True, default=django.utils.timezone.localdate)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
