# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate),
        ),
    ]
