# Generated by Django 2.2.4 on 2019-08-20 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import seller.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_title', models.TextField(max_length=300)),
                ('category', models.ManyToManyField(to='seller.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SearchTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_tag', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_text', models.TextField(max_length=500)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Gig')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('details_offering', models.TextField(max_length=300)),
                ('delivery_time', models.IntegerField(max_length=50)),
                ('revisions', models.IntegerField(max_length=20)),
                ('price', models.IntegerField(max_length=20)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Gig')),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='search_tag',
            field=models.ManyToManyField(to='seller.SearchTag'),
        ),
        migrations.AddField(
            model_name='gig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_image', models.ImageField(upload_to=seller.models.gig_gallery_images_path)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Gig')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=400)),
                ('answer', models.TextField(max_length=400)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Gig')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Gig')),
            ],
        ),
    ]
