# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.Course')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='grade.Grade')),
            ],
        ),
    ]
