// Author Actions
export const FETCH_AUTHOR_SUCCESS = "FETCH_AUTHOR_SUCCESS"
export const FETCH_AUTHOR_FAILURE = "FETCH_AUTHOR_FAILURE"
export const FETCH_AUTHOR_STARTED = "FETCH_AUTHOR_STARTED"

export const FETCH_AUTHORS_SUCCESS = "FETCH_AUTHORS_SUCCESS"
export const FETCH_AUTHORS_FAILURE = "FETCH_AUTHORS_FAILURE"
export const FETCH_AUTHORS_STARTED = "FETCH_AUTHORS_STARTED"

export const CREATE_AUTHOR_SUCCESS = "CREATE_AUTHOR_SUCCESS"
export const CREATE_AUTHOR_FAILURE = "CREATE_AUTHOR_FAILURE"
export const CREATE_AUTHOR_STARTED = "CREATE_AUTHOR_STARTED"

export const UPDATE_AUTHOR_SUCCESS = "UPDATE_AUTHOR_SUCCESS"
export const UPDATE_AUTHOR_FAILURE = "UPDATE_AUTHOR_FAILURE"
export const UPDATE_AUTHOR_STARTED = "UPDATE_AUTHOR_STARTED"

export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS"
export const DELETE_AUTHOR_FAILURE = "DELETE_AUTHOR_FAILURE"
export const DELETE_AUTHOR_STARTED = "DELETE_AUTHOR_STARTED"
