// Auth Actions
const AUTH = {
  FETCH_USER_STARTED: "FETCH_USER_STARTED",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_FAILURE: "FETCH_USER_FAILURE",

  SIGNUP_AUTHOR_STARTED: "SIGNUP_AUTHOR_STARTED",
  SIGNUP_AUTHOR_SUCCESS: "SIGNUP_AUTHOR_SUCCESS",
  SIGNUP_AUTHOR_FAILURE: "SIGNUP_AUTHOR_FAILURE",

  SIGNUP_PUBLISHER_STARTED: "SIGNUP_PUBLISHER_STARTED",
  SIGNUP_PUBLISHER_SUCCESS: "SIGNUP_PUBLISHER_SUCCESS",
  SIGNUP_PUBLISHER_FAILURE: "SIGNUP_PUBLISHER_FAILURE",

  LOGIN_STARTED: "LOGIN_STARTED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_STARTED: "LOGOUT_STARTED",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE"
}

export default AUTH
