// Auth Actions
export const FETCH_USER_STARTED = "FETCH_USER_STARTED"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE"

export const SIGNUP_AUTHOR_STARTED = "SIGNUP_AUTHOR_STARTED"
export const SIGNUP_AUTHOR_SUCCESS = "SIGNUP_AUTHOR_SUCCESS"
export const SIGNUP_AUTHOR_FAILURE = "SIGNUP_AUTHOR_FAILURE"

export const SIGNUP_PUBLISHER_STARTED = "SIGNUP_PUBLISHER_STARTED"
export const SIGNUP_PUBLISHER_SUCCESS = "SIGNUP_PUBLISHER_SUCCESS"
export const SIGNUP_PUBLISHER_FAILURE = "SIGNUP_PUBLISHER_FAILURE"

export const LOGIN_AUTHOR_STARTED = "LOGIN_AUTHOR_STARTED"
export const LOGIN_AUTHOR_SUCCESS = "LOGIN_AUTHOR_SUCCESS"
export const LOGIN_AUTHOR_FAILURE = "LOGIN_AUTHOR_FAILURE"

export const LOGIN_PUBLISHER_STARTED = "LOGIN_PUBLISHER_STARTED"
export const LOGIN_PUBLISHER_SUCCESS = "LOGIN_PUBLISHER_SUCCESS"
export const LOGIN_PUBLISHER_FAILURE = "LOGIN_PUBLISHER_FAILURE"
