// Author Actions
const AUTHOR = {
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",

  FETCH_AUTHOR_STARTED: "FETCH_AUTHOR_STARTED",
  FETCH_AUTHOR_SUCCESS: "FETCH_AUTHOR_SUCCESS",
  FETCH_AUTHOR_FAILURE: "FETCH_AUTHOR_FAILURE",

  FETCH_AUTHORS_DATA_STARTED: "FETCH_AUTHORS_DATA_STARTED",
  FETCH_AUTHORS_DATA_SUCCESS: "FETCH_AUTHORS_DATA_SUCCESS",
  FETCH_AUTHORS_DATA_FAILURE: "FETCH_AUTHORS_DATA_FAILURE",

  FETCH_AUTHORS_STARTED: "FETCH_AUTHORS_STARTED",
  FETCH_AUTHORS_SUCCESS: "FETCH_AUTHORS_SUCCESS",
  FETCH_AUTHORS_FAILURE: "FETCH_AUTHORS_FAILURE",

  UPDATE_AUTHOR_STARTED: "UPDATE_AUTHOR_STARTED",
  UPDATE_AUTHOR_SUCCESS: "UPDATE_AUTHOR_SUCCESS",
  UPDATE_AUTHOR_FAILURE: "UPDATE_AUTHOR_FAILURE",

  DELETE_AUTHOR_STARTED: "DELETE_AUTHOR_STARTED",
  DELETE_AUTHOR_SUCCESS: "DELETE_AUTHOR_SUCCESS",
  DELETE_AUTHOR_FAILURE: "DELETE_AUTHOR_FAILURE"
}

export default AUTHOR
