// Book Actions
export const FETCH_BOOK_SUCCESS = "FETCH_BOOK_SUCCESS"
export const FETCH_BOOK_FAILURE = "FETCH_BOOK_FAILURE"
export const FETCH_BOOK_STARTED = "FETCH_BOOK_STARTED"

export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS"
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE"
export const FETCH_BOOKS_STARTED = "FETCH_BOOKS_STARTED"

export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS"
export const CREATE_BOOK_FAILURE = "CREATE_BOOK_FAILURE"
export const CREATE_BOOK_STARTED = "CREATE_BOOK_STARTED"

export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS"
export const UPDATE_BOOK_FAILURE = "UPDATE_BOOK_FAILURE"
export const UPDATE_BOOK_STARTED = "UPDATE_BOOK_STARTED"

export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS"
export const DELETE_BOOK_FAILURE = "DELETE_BOOK_FAILURE"
export const DELETE_BOOK_STARTED = "DELETE_BOOK_STARTED"
