// Category Actions
const CATEGORY = {
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",

  FETCH_CATEGORY_STARTED: "FETCH_CATEGORY_STARTED",
  FETCH_CATEGORY_SUCCESS: "FETCH_CATEGORY_SUCCESS",
  FETCH_CATEGORY_FAILURE: "FETCH_CATEGORY_FAILURE",

  FETCH_CATEGORIES_STARTED: "FETCH_CATEGORIES_STARTED",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILURE: "FETCH_CATEGORIES_FAILURE",

  FETCH_CATEGORIES_DATA_STARTED: "FETCH_CATEGORIES_DATA_STARTED",
  FETCH_CATEGORIES_DATA_SUCCESS: "FETCH_CATEGORIES_DATA_SUCCESS",
  FETCH_CATEGORIES_DATA_FAILURE: "FETCH_CATEGORIES_DATA_FAILURE",

  CREATE_CATEGORY_STARTED: "CREATE_CATEGORY_STARTED",
  CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
  CREATE_CATEGORY_FAILURE: "CREATE_CATEGORY_FAILURE",

  UPDATE_CATEGORY_STARTED: "UPDATE_CATEGORY_STARTED",
  UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",

  DELETE_CATEGORY_STARTED: "DELETE_BOOK_STARTED",
  DELETE_CATEGORY_SUCCESS: "DELETE_BOOK_SUCCESS",
  DELETE_CATEGORY_FAILURE: "DELETE_BOOK_FAILURE"
}

export default CATEGORY
