// Category Actions
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS"
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE"
export const FETCH_CATEGORY_STARTED = "FETCH_CATEGORY_STARTED"

export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS"
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE"
export const FETCH_CATEGORIES_STARTED = "FETCH_CATEGORIES_STARTED"

export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS"
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE"
export const CREATE_CATEGORY_STARTED = "CREATE_CATEGORY_SUCCESS"

export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS"
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE"
export const UPDATE_CATEGORY_STARTED = "UPDATE_CATEGORY_STARTED"

export const DELETE_CATEGORY_SUCCESS = "DELETE_BOOK_SUCCESS"
export const DELETE_CATEGORY_FAILURE = "DELETE_BOOK_FAILURE"
export const DELETE_CATEGORY_STARTED = "DELETE_BOOK_STARTED"
