// Publisher Actions
export const FETCH_PUBLISHER_SUCCESS = "FETCH_PUBLISHER_SUCCESS"
export const FETCH_PUBLISHER_FAILURES = "FETCH_PUBLISHER_FAILURE"
export const FETCH_PUBLISHER_STARTED = "FETCH_PUBLISHER_STARTED"

export const FETCH_PUBLISHERS_SUCCESS = "FETCH_PUBLISHERS_SUCCESS"
export const FETCH_PUBLISHERS_FAILURE = "FETCH_PUBLISHERS_FAILURE"
export const FETCH_PUBLISHERS_SUTARTED = "FETCH_PUBLISHERS_STARTED"

export const CREATE_PUBLISHER_SUCCESS = "CREATE_PUBLISHER_SUCCESS"
export const CREATE_PUBLISHER_FAILURE = "CREATE_PUBLISHER_FAILURE"
export const CREATE_PUBLISHER_SUTARTED = "CREATE_PUBLISHER_STARTED"

export const UPDATE_PUBLISHER_SUCCESS = "UPDATE_PUBLISHER_SUCCESS"
export const UPDATE_PUBLISHER_FAILURE = "UPDATE_PUBLISHER_FAILURE"
export const UPDATE_PUBLISHER_SUTARTED = "UPDATE_PUBLISHER_STARTED"

export const DELETE_PUBLISHER_SUCCESS = "DELETE_PUBLISHER_SUCCESS"
export const DELETE_PUBLISHER_FAILURE = "DELETE_PUBLISHER_FAILURE"
export const DELETE_PUBLISHER_SUTARTED = "DELETE_PUBLISHER_STARTED"
