# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 06:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import twitter.models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='published date')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', twitter.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
