# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20170724_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
