# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20170725_0837'),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
