# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20170726_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='tweet',
            table='tweet',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
