# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20170727_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-pub_date',)},
        ),
    ]
