# Generated by Django 2.2.4 on 2019-08-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_full_name'),
        ('shop', '0002_saloon_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preservation',
            new_name='Reservation',
        ),
    ]
