# Generated by Django 2.2.4 on 2019-09-04 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Retailer_Sku', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=50)),
                ('Url', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('Care', models.CharField(max_length=1000)),
                ('Out_of_stock', models.CharField(max_length=10)),
                ('Image_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sku_id', models.CharField(max_length=50)),
                ('Size', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=50)),
                ('Currency', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
                ('Retailer_Sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fila.Product')),
            ],
        ),
    ]
