# Generated by Django 2.2.4 on 2019-09-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fila', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sku',
            new_name='Skus',
        ),
    ]
