# Generated by Django 2.2.4 on 2019-09-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fila', '0002_auto_20190904_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
