# Generated by Django 2.2.4 on 2019-09-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fila', '0004_auto_20190904_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Care',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Out_of_stock',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
