# Generated by Django 2.2.4 on 2019-09-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fila', '0006_auto_20190904_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image_url',
            field=models.CharField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='skus',
            name='Color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skus',
            name='Price',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='skus',
            name='Sku_id',
            field=models.CharField(max_length=1000),
        ),
    ]
