# Generated by Django 2.2.4 on 2019-09-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fila', '0007_auto_20190904_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='Retailer_Sku',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
