# Generated by Django 2.2.8 on 2019-12-06 14:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('publishers', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateField(default=django.utils.timezone.now)),
                ('isbn', models.CharField(db_index=True, default=None, max_length=13, unique=True)),
                ('pages', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(db_index=True, default=None, max_length=200)),
                ('authors', models.ManyToManyField(related_name='books', to='authors.Author')),
                ('categories', models.ManyToManyField(related_name='books', to='categories.Category')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='publishers.Publisher')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
