# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20180115_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
