# Generated by Django 2.2.6 on 2019-10-24 10:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20191024_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='published_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 10, 24, 10, 3, 51, 662030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
