# Generated by Django 2.2.6 on 2019-10-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20191024_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='thumbnail',
            field=models.ImageField(default='default_note_thumb.png', upload_to='note_book_thumbnails'),
        ),
    ]
