# Generated by Django 2.0.3 on 2018-04-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0004_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bider_user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
