# Generated by Django 2.0.3 on 2018-04-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_bids_bider_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='BidValue',
            new_name='bid_amount',
        ),
        migrations.AddField(
            model_name='bids',
            name='status',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
