# Generated by Django 2.0.3 on 2018-04-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0006_auto_20180404_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
