# Generated by Django 2.0.3 on 2018-04-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0007_auto_20180404_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='project_status',
            field=models.CharField(default='Not Hired', max_length=100),
        ),
    ]
