# Generated by Django 2.2.4 on 2019-08-16 10:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(default=-1, upload_to=accounts.models.profile_images_path),
            preserve_default=False,
        ),
    ]
