# -*- coding = Field()utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html
from scrapy import Field, Item


class ProductItem(Item):
    new_price_text = Field()
    _item_id = Field()
    gender_names = Field()
    category_names = Field()
    upc = Field()
    currency = Field()
    referer_url = Field()
    gtin = Field()
    size_infos = Field()
    country_code = Field()
    language_code = Field()
    keywords = Field()
    additional_info_dict = Field() 
    sku = Field()
    full_price_text = Field()
    additional_attributes = Field() 
    webshop = Field()
    title = Field()
    base_sku = Field()
    measurements = Field()
    save_availability = Field()
    rgb = Field()
    old_price_text = Field()
    season = Field()
    third_party_vendor = Field()
    _response = Field()
    available = Field()
    old_identifier = Field()
    _current_price_value = Field()
    full_price_value = Field()
    color_code = Field()
    category_identifiers = Field()
    timestamp = Field()
    brand = Field()
    material = Field()
    image_urls = Field()
    max_original_price_value = Field()
    add_category_and_gender = Field()
    update_details = Field()
    max_current_price_value = Field()
    description_text = Field()
    product_id = Field()
    category_levels = Field()
    _original_price_value = Field()
    gender_identifiers = Field()
    image_subdir = Field()
    url = Field()
    product_stock = Field()
    new_price_value = Field()
    category_parents = Field()
    use_size_level_prices = Field()
    save_price = Field()
    color_name = Field()
    _discount = Field()
    pattern = Field()
    old_price_value = Field()
    identifier = Field()
    image_descriptions = Field()


class SizeInfosItem(Item):
    size_name = Field()
    size_identifier = Field()
    stock = Field()
