# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 05:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import educare.managers
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('biography', models.TextField(max_length=200, null=True)),
                ('profile_picture', models.ImageField(default='img_folder/default.jpeg', upload_to='img_folder/')),
                ('location', models.CharField(choices=[('LHR', 'Lahore'), ('FSD', 'Faisalabad'), ('KHI', 'Karachi'), ('ISL', 'Islamabad'), ('PEW', 'Peshawar'), ('MUL', 'Multan')], max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('user_type', models.CharField(choices=[('T', 'Tutor'), ('S', 'Student')], max_length=1)),
                ('subjects', models.CharField(choices=[('Math', 'Mathematics'), ('Eng', 'English'), ('Bio', 'Biology'), ('Chem', 'Chemistry'), ('Phy', 'Physics'), ('Acc', 'Accounting'), ('BStd', 'Business Studies'), ('Eco', 'Economics')], default='', max_length=4)),
            ],
            options={
                'verbose_name': 'user',
                'managed': True,
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', educare.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grade', models.CharField(choices=[('PreNur', 'Pre-Nursery'), ('Nur', 'Nursery'), ('KG', 'Kindergarten'), ('GR-1', 'Grade 1'), ('GR-2', 'Grade 2'), ('GR-3', 'Grade 3'), ('GR-4', 'Grade 4'), ('GR-5', 'Grade 5'), ('GR-6', 'Grade 6'), ('GR-7', 'Grade 7'), ('GR-8', 'Grade 8'), ('MAT-9', 'Matric Grade 9'), ('MAT-10', 'Matric Grade 10'), ('OL-9', 'Olevels Grade 9'), ('OL-10', 'Olevels Grade 10'), ('OL-11', 'Olevels Grade 11')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('educare.user',),
            managers=[
                ('objects', educare.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('education', models.TextField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+92', max_length=128)),
            ],
            options={
                'abstract': False,
            },
            bases=('educare.user',),
            managers=[
                ('objects', educare.managers.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
