# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 06:14
from __future__ import unicode_literals

from django.db import migrations
import educare.managers


class Migration(migrations.Migration):

    dependencies = [
        ('educare', '0002_auto_20170724_0608'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objects', educare.managers.CustomUserManager()),
            ],
        ),
    ]
