# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 09:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educare', '0005_auto_20170725_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), size=None),
        ),
    ]
