# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170706_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Person',
        ),
    ]
