# Generated by Django 2.1.7 on 2019-04-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190416_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='blog_text',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='contents',
            name='status',
            field=models.IntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1),
        ),
    ]
