# Generated by Django 2.1.7 on 2019-04-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190417_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='user_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
