# Generated by Django 2.1.7 on 2019-04-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_contents_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contents',
            new_name='Blog',
        ),
    ]
