# Generated by Django 2.1.7 on 2019-04-24 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0005_auto_20190423_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user_name',
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.OneToOneField(default='null', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
