# Generated by Django 2.1.7 on 2019-04-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20190424_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user',
        ),
        migrations.AddField(
            model_name='blog',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='user_name',
            field=models.CharField(default='abdullah', max_length=200),
            preserve_default=False,
        ),
    ]
