# Generated by Django 2.2.5 on 2019-10-04 12:08

import accounts.models
import accounts.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbuser',
            name='profile_picture',
            field=models.ImageField(storage=accounts.utils.storage.OverwriteStorage(), upload_to=accounts.models.upload_location),
        ),
    ]
