# Generated by Django 2.1 on 2018-08-20 06:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_auto_20180820_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IL', 'Inappropriate language'), ('FA', 'Fake account'), ('MS', 'Misuse of service'), ('OT', 'Other')], max_length=2)),
                ('comments', models.TextField(max_length=500)),
                ('date_logged', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to='accounts.UserProfile')),
                ('reporting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_report', to='accounts.UserProfile')),
            ],
        ),
    ]
