# Generated by Django 2.2.dev20180707212002 on 2018-07-19 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crickethome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlefollows',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='teamfollows',
            name='player_id',
        ),
        migrations.AddField(
            model_name='articlefollows',
            name='article_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crickethome.Article'),
        ),
        migrations.AddField(
            model_name='teamfollows',
            name='team_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crickethome.Team'),
        ),
        migrations.AlterField(
            model_name='articlecomments',
            name='article_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crickethome.Article'),
        ),
        migrations.AlterField(
            model_name='playercomments',
            name='player_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crickethome.Player'),
        ),
        migrations.AlterField(
            model_name='playerfollows',
            name='player_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crickethome.Player'),
        ),
        migrations.AlterField(
            model_name='playerphotos',
            name='player_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crickethome.Player'),
        ),
        migrations.AlterField(
            model_name='teamcomments',
            name='team_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crickethome.Team'),
        ),
    ]
