# Generated by Django 2.2.dev20180707212002 on 2018-07-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crickethome', '0002_auto_20180719_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='DOB',
            new_name='born',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Author', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='Description', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='articlecomments',
            name='comment_text',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='battingaverages',
            name='average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='battingaverages',
            name='balls_faced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingaverages',
            name='catches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingaverages',
            name='fifties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingaverages',
            name='fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingaverages',
            name='highest_score',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='battingaverages',
            name='hundreds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingaverages',
            name='innings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingaverages',
            name='match_format',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='battingaverages',
            name='matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingaverages',
            name='not_outs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingaverages',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingaverages',
            name='sixes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingaverages',
            name='strike_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='battingaverages',
            name='stumps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingaverages',
            name='average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingaverages',
            name='balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingaverages',
            name='best_bowling_innings',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='bowlingaverages',
            name='best_bowling_match',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='bowlingaverages',
            name='economy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingaverages',
            name='five_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingaverages',
            name='four_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingaverages',
            name='innings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingaverages',
            name='match_format',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='bowlingaverages',
            name='matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingaverages',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingaverages',
            name='strike_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingaverages',
            name='ten_wickets_in_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingaverages',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='batting_style',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='bowling_style',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='major_team',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='playing_role',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='url',
            field=models.URLField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='playercomments',
            name='comment_text',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='playerphotos',
            name='photo_url',
            field=models.URLField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='url',
            field=models.URLField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='teamcomments',
            name='comment_text',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.URLField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(default='simple', max_length=50),
        ),
    ]
