# Generated by Django 2.1.1 on 2018-09-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Manager', 'Manager'), ('Worker', 'Worker')], default='Worker', max_length=10),
        ),
    ]
