# Generated by Django 2.1.1 on 2018-09-14 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalApp', '0002_auto_20180914_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competency',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppraisalApp.Feedback', unique=True),
        ),
    ]
