# Generated by Django 2.1.1 on 2018-09-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppraisalApp', '0003_auto_20180914_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.IntegerField(blank=True, choices=[(1, 'CEO'), (2, 'Manager'), (3, 'Worker')], default=3),
        ),
    ]
