# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='published date'),
        ),
    ]
