# Generated by Django 2.0 on 2018-09-11 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2018, 9, 18, 13, 23, 36, 557296), verbose_name='Due Date'),
        ),
    ]
