# Generated by Django 2.0 on 2018-08-06 13:22

import datetime
from django.db import migrations, models
import taskmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_auto_20180806_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='media/profile.jpg', upload_to=taskmanager.models.upload),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 13, 13, 22, 19, 820642), verbose_name='Due Date'),
        ),
    ]
