# Generated by Django 2.0 on 2018-08-16 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0006_auto_20180808_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 23, 7, 45, 30, 996274), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(),
        ),
    ]
