# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 17:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('retailer_sku', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('care', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), blank=True, null=True, size=8)),
            ],
        ),
    ]
