# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='retailer_sku',
            field=models.BigIntegerField(),
        ),
    ]
