# Generated by Django 2.1 on 2018-08-15 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180811_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pairId',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pair_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
