# Generated by Django 2.1 on 2018-08-27 11:32

import accounts.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_display_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_paired', models.BooleanField(default=True)),
                ('date_logged', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('unpaired_by', models.CharField(choices=[('DN', 'Donor'), ('CN', 'Consumer')], max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_picture',
            field=models.ImageField(null=True, upload_to=accounts.models.file_path_and_rename),
        ),
        migrations.AddField(
            model_name='pairhistory',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_pair_history', to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='pairhistory',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_pair_history', to='accounts.UserProfile'),
        ),
    ]
