# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='colorurl',
            table='color_url',
        ),
        migrations.AlterModelTable(
            name='imageurl',
            table='image_url',
        ),
        migrations.AlterModelTable(
            name='sku',
            table='sku',
        ),
    ]
