# Generated by Django 2.2.4 on 2019-09-17 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190917_0950'),
        ('payment', '0002_remove_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='users.Order'),
        ),
    ]
