# Generated by Django 2.2.4 on 2019-09-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='succeeded', max_length=100),
            preserve_default=False,
        ),
    ]
