# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_auto_20170707_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='nps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='satisfaction_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
