# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_auto_20170711_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedbacks',
            name='department',
        ),
        migrations.RemoveField(
            model_name='feedbacks',
            name='store',
        ),
        migrations.AddField(
            model_name='store',
            name='Feedbacks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbacks.Feedbacks'),
        ),
        migrations.AddField(
            model_name='department',
            name='Feedbacks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbacks.Feedbacks'),
        ),
    ]
