# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_auto_20170711_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='Feedbacks',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Feedbacks',
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbacks.Department'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbacks.Store'),
        ),
    ]
