# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_auto_20170711_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
