# Generated by Django 2.2.3 on 2019-07-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Business', 'Business'), ('Sports', 'Sports'), ('Education', 'Education'), ('Science', 'Science'), ('International', 'International'), ('Entertainment', 'Entertainment'), ('Lifestyle', 'Lifestyle'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=13)),
                ('content', models.TextField()),
                ('publish_time', models.DateTimeField()),
                ('url', models.URLField(max_length=400, unique=True)),
                ('authors', models.ManyToManyField(related_name='authors', to='articles.Author')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='articles.Website')),
            ],
        ),
    ]
