# Generated by Django 2.2.3 on 2019-07-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='image_url',
        ),
    ]
