# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.3 on 2017-07-14 10:21
from __future__ import unicode_literals

from django.conf import settings
=======
# Generated by Django 1.11.3 on 2017-07-13 11:40
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
>>>>>>> d6e8908... Adding Main Models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        ('auth', '0008_alter_user_username_max_length'),
>>>>>>> d6e8908... Adding Main Models
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('text', models.TextField()),
                ('summary', models.TextField()),
                ('created_on', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('comments_allowed', models.BooleanField(default=True)),
                ('is_public', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField()),
                ('user_ip', models.GenericIPAddressField()),
                ('comment_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wblog.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
            name='UserInfo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
>>>>>>> d6e8908... Adding Main Models
                ('phone_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('image', models.ImageField(upload_to='./user-images/')),
                ('created_at', models.DateTimeField()),
<<<<<<< HEAD
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wblog.UserInfo'),
        ),
        migrations.AddField(
            model_name='blog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wblog.UserInfo'),
=======
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
>>>>>>> d6e8908... Adding Main Models
        ),
    ]
