# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('text', models.TextField()),
                ('summary', models.TextField()),
                ('created_on', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('comments_allowed', models.BooleanField(default=True)),
                ('is_public', models.BooleanField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wblog.UserInfo')),
            ],
        ),
    ]
