# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, error_messages={'error': 'Invalid Gender'}, max_length=1),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, default='user.png', upload_to='./user-images/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
