# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wblog', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField()),
                ('user_ip', models.GenericIPAddressField()),
                ('comment_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wblog.Blog')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wblog.UserInfo')),
            ],
        ),
    ]
