# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171115_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_comment',
            name='vote',
            field=models.IntegerField(default=-1, verbose_name=((1, 'up_vote'), (-1, 'down_vote'))),
        ),
        migrations.AlterField(
            model_name='like_post',
            name='vote',
            field=models.IntegerField(default=-1, verbose_name=((1, 'up_vote'), (-1, 'down_vote'))),
        ),
    ]
