# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171115_0741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like_comment',
            new_name='LikeComment',
        ),
        migrations.RenameModel(
            old_name='Like_post',
            new_name='LikePost',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
