# Generated by Django 2.1 on 2018-08-20 06:28

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_auto_20180820_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, max_length=350)),
                ('date_logged', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('given_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to='accounts.UserProfile')),
                ('given_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to='accounts.UserProfile')),
            ],
        ),
    ]
