# Generated by Django 2.2.5 on 2019-09-11 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('image_identifier', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to=portal.models.update_filename)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
