# Generated by Django 2.2.5 on 2019-09-12 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotes',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Profile'),
        ),
        migrations.CreateModel(
            name='Downvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downvoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_downvoter', to='portal.Profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Profile')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Uploads')),
            ],
        ),
    ]
