# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_appraisal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='year',
            field=models.IntegerField(choices=[(2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017),
        ),
    ]
