# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_appraisal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
