# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_appraisal_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appraisal',
            unique_together=set([('year', 'employee')]),
        ),
    ]
