# Generated by Django 2.2.6 on 2019-10-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='contact',
            new_name='phone_number',
        ),
    ]
