# Generated by Django 2.2.6 on 2019-10-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20191022_1011'),
        ('users', '0004_auto_20191021_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='books_issued',
            field=models.ManyToManyField(max_length=3, null=True, to='books.Book', verbose_name='list of books'),
        ),
    ]
