# Generated by Django 2.2.6 on 2019-10-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_books_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='books_issued',
            field=models.ManyToManyField(blank=True, max_length=3, to='books.Book', verbose_name='list of books'),
        ),
    ]
