# Generated by Django 2.2.6 on 2019-10-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20191022_1011'),
        ('users', '0006_auto_20191022_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='books_issued',
        ),
        migrations.CreateModel(
            name='BooksIssued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_issued', models.ManyToManyField(blank=True, max_length=3, to='books.Book')),
            ],
        ),
    ]
