# Generated by Django 2.2.6 on 2019-10-23 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191023_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='books_issued',
            field=models.ForeignKey(max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
    ]
