# Generated by Django 2.2.6 on 2019-10-23 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20191023_0809'),
        ('users', '0012_auto_20191023_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='book_issued',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='books',
            field=models.ForeignKey(max_length=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.Book'),
        ),
    ]
