# Generated by Django 2.2.6 on 2019-10-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191023_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='books',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='book_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
