# Generated by Django 2.2.6 on 2019-10-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191024_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='book_count',
        ),
    ]
