# Generated by Django 2.2.6 on 2019-10-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile_book_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='book_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
