# Generated by Django 2.2.6 on 2019-10-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20191024_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='book_count',
            field=models.IntegerField(default=0),
        ),
    ]
