# Generated by Django 2.2.6 on 2019-10-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20191024_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='book_count',
        ),
    ]
