categories = 'div.text.parbase.section>p>a, div.text.parbase.section>h3>a'
sub_categories = 'div.text.parbase.section>ul>li>a'
list_type_1 = 'div.row-fluid.product-header>div>a'
list_type_2 = 'div.result.catalog.search-card.active-prod-card.OneLinkNoTx>a'
get_additional_info_url = 'https://www.thermofisher.com/order/catalog/en/US/adirect/lt?' \
                          'cmd=commercePodOperations&productID={}&operation=Price'
get_documents_info_url = 'https://www.thermofisher.com/search/api/documents/sku/en/pk/{}?docTypes=COA,MSDS,' \
                         'Manuals,Protocols,LULL,Brochures,Probes%20Structure,Vectors,CellLines,Posters,Unitrays,' \
                         'MediaFormulation,TechBulletins,,Probes%20Spectra,Probes%20Handbook,FAQ,SupportFiles%26'

get_documents_info_url_multiple = 'http://www.thermofisher.com/search/api/documents/family/en/pk/{}?docTypes=MSDS,' \
                                'Manuals,Protocols,Brochures,Posters,FAQ '

product_type = '.pdp-segmentation-control.active h4::text'
product_type_2 = '#pfp-commerce-action-bar'
breadcrumbs_sel = 'ul.breadcrumb li span[itemprop="name"]::text'
breadcrumbs_sel_2 = 'ul.breadcrumb > li>a::text,ul.breadcrumb > li::text'
img_src_sel = '#pdp-product-image::attr(src)'
get_cid_1 = 'span.catNum[itemprop="sku"]::text'
get_cid_2 = 'span[itemprop="sku"]::text'
get_name_1 = 'h1.pageheader::text'
get_name_2 = 'h1[itemprop="name"] ::text'
get_price_amount = '#pdp-catalog-table tr>td span.price-amount::text'
get_price_quote = '#pdp-catalog-table tr>td span.price-link ::text'
get_price_3 = 'span.price::text'
get_sizes = '#pdp-catalog-table tr>td[class="attr"]::text'
get_cat_ids = '#pdp-catalog-table tr>td[webId]::text'
is_parsable_list = '#productForm'
get_description_1 = '#pdp-description-wrapper ::text'
get_description_2 = '#pdp-description-right ::text'
list_type_identifier = 'li#Catalog'
list_type_2_next = 'a[class="next"]'
list_type_1_post_url = 'https://www.thermofisher.com/order/genome-database/browse/antibody/sub-type/getJSONResult'
list_1_total_hits = '#numHits::attr(value)'
list_1_body_script_tag = 'body>script'
v_num_regex = "lt_rev='(\w+)'"
product_type_2_description = '#pdp-description ::text'
product_type_2_recommended_products_check = '#pdp-cross-sell'
product_type_2_recommend_urls = '#pdp-cross-sell div.panel-heading>a::attr(href)'
product_type_2_recommend_catalogs = '#pdp-cross-sell a[data-sku]::attr(data-sku)'
product_type_2_specifications_check = '#pdp-specifications-table'
product_type_2_specifications_keys = '#pdp-specifications-table th::text'
product_type_2_specifications_vals = '#pdp-specifications-table td::text'
product_type_2_contents_check = '#pdp-contents-storage'
product_type_2_contents = '#pdp-contents-storage ::text'
product_type_2_related_apps = 'div.pdp-badge>p>a::text'
get_brand = 'span[itemprop="brand"]::text'
product_type_1_formatted_sku = 'input.sku_input::attr(value)'
product_type_1_functions_check = '#goProcessSection'
product_type_1_functions = '#goProcessSection a'
product_type_1_processes_check = '#goFunctionSection'
product_type_1_processes = '#goFunctionSection a'
product_type_1_secondaries_check = 'div.secondary-cross-sell-box'
product_type_1_secondaries = 'div.secondary-cross-sell-box a'
product_type_1_images = '#pdp-product-thumbgallery a'
product_type_1_image_title = '::attr(data-headline)'
product_type_1_image_url = '::attr(href)'
product_type_1_image_description = '::attr(data-title)'
product_type_1_specs = 'table.table-specifications'
product_type_1_specs_data = 'thead th.header-left::text'
product_type_1_table_to_dict_keys = 'th.cell-title::text'
product_type_1_table_to_dict_values = 'td.cell-content'
product_type_1_specifications = 'div.product-specification-information-segment p::text'
product_type_1_background_info = 'div.background-information-segment p::text'
product_type_1_bioinformatics_check = '#pdp-bioinformatics'
product_type_1_bioinformatics = '#pdp-bioinformatics div.bioinformatics-sub-section ::text'
get_td_text = 'td::text'
get_td = 'td'
get_table_body_tr = 'table tbody>tr'
product_type_1_references = 'div.tab-pane'
get_attr_id = '::attr(id)'
get_a_text = 'a::text'
get_a_attr_href = 'a::attr(href)'
get_all_text = ' ::text'
get_original_product_type = '#originalProductType::attr(value)'
get_original_species = '#originalSpecies::attr(value)'
get_originat_target_type = '#originalTargetType::attr(value)'
get_family_id = '#productDisplayPageApplicationWrapper::attr(data-omni-title)'
get_cid_type_3 = 'input[name="LoginData-productID"]::attr(value)'
get_images_type_3 = 'div#product-thumbnails a::attr(href)'
get_type_3_product_data = '//script[contains(text(),"window.preloadData")]'
get_price_info_url = 'http://www.thermofisher.com/order/catalog/en/US/adirect/lt?cmd=getPricingData&operation=Price' \
                     '&products={} '
