# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
