# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
    ]
