# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0002_auto_20170706_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='user_id',
            new_name='user',
        ),
    ]
