# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 02:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0002_auto_20170720_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_perm',
        ),
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 2, 25, 28, 337787, tzinfo=utc)),
        ),
    ]
