# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoapp', '0003_auto_20170706_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
