# -*- coding: utf-8 -*-
from scrapy import Item, Field


class TrigemaItem(Item):
    ownership = Field()
    project = Field()
    developer = Field()
    locality = Field()
    gps = Field()
    energy_class = Field()
    type = Field()
    finished = Field()
    cellar = Field()
    number = Field()
    local_id = Field()
    detail_url = Field()
    timestamp = Field()
    building = Field()
    floor = Field()
    disposition = Field()
    usable_area = Field()
    terrace = Field()
    storeroom = Field()
    state = Field()
    parking = Field()
    price = Field()
    price_excluding_vat = Field()
    orientation = Field()
    floor_area = Field()
    balcony = Field()
    indoor_garden = Field()
    garden = Field()
    room = Field()
