# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-09 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateTimeField()),
                ('contact_number', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('skill1', models.CharField(max_length=30, null=True)),
                ('skill2', models.CharField(max_length=30, null=True)),
                ('skill3', models.CharField(max_length=30, null=True)),
                ('skill4', models.CharField(max_length=30, null=True)),
                ('skill5', models.CharField(max_length=30, null=True)),
                ('skill1_level', models.CharField(choices=[(1, 'Beginner'), (2, 'Little Knowledge'), (3, 'Intermediate'), (4, 'Advance'), (5, 'Expert')], max_length=30, null=True)),
                ('skill2_level', models.CharField(choices=[(1, 'Beginner'), (2, 'Little Knowledge'), (3, 'Intermediate'), (4, 'Advance'), (5, 'Expert')], max_length=30, null=True)),
                ('skill3_level', models.CharField(choices=[(1, 'Beginner'), (2, 'Little Knowledge'), (3, 'Intermediate'), (4, 'Advance'), (5, 'Expert')], max_length=30, null=True)),
                ('skill4_level', models.CharField(choices=[(1, 'Beginner'), (2, 'Little Knowledge'), (3, 'Intermediate'), (4, 'Advance'), (5, 'Expert')], max_length=30, null=True)),
                ('skill5_level', models.CharField(choices=[(1, 'Beginner'), (2, 'Little Knowledge'), (3, 'Intermediate'), (4, 'Advance'), (5, 'Expert')], max_length=30, null=True)),
                ('hobby1', models.CharField(max_length=30, null=True)),
                ('hobby2', models.CharField(max_length=30, null=True)),
                ('hobby3', models.CharField(max_length=30, null=True)),
                ('reference1', models.CharField(max_length=30, null=True)),
                ('reference2', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('degree', models.CharField(max_length=30)),
                ('institute', models.CharField(max_length=100)),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField(null=True)),
                ('city', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_maker_app.BasicInformation')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('organization', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('starting_date', models.DateTimeField()),
                ('ending_date', models.DateTimeField(null=True)),
                ('job_description', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=30)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_maker_app.BasicInformation')),
            ],
        ),
    ]
