# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-10 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker_app', '0002_auto_20190710_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='ending_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='starting_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='starting_date',
            field=models.DateField(),
        ),
    ]
