# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-10 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker_app', '0004_auto_20190710_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinformation',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
