# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-11 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker_app', '0007_auto_20190710_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformation',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
