# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-12 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker_app', '0008_auto_20190711_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinformation',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
