# Generated by Django 2.2.3 on 2019-07-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker_app', '0009_auto_20190712_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
                ('skill1', models.CharField(max_length=30)),
                ('skill2', models.CharField(max_length=30)),
                ('skill3', models.CharField(max_length=30)),
            ],
        ),
    ]
