# Generated by Django 2.2.3 on 2019-07-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_maker_app', '0011_auto_20190717_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinformation',
            name='skill1_level',
        ),
        migrations.RemoveField(
            model_name='basicinformation',
            name='skill2_level',
        ),
        migrations.RemoveField(
            model_name='basicinformation',
            name='skill3_level',
        ),
        migrations.RemoveField(
            model_name='basicinformation',
            name='skill4_level',
        ),
        migrations.RemoveField(
            model_name='basicinformation',
            name='skill5_level',
        ),
    ]
