# Generated by Django 2.2.4 on 2019-08-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    def add_users(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        User = apps.get_model('user_profile', 'User')
        User(username='asim',
             password='asim123',
             email='asim@gmail.com'
             ).save()
        User(username='azhar',
             password='azhar123',
             email='azhar@gmail.com'
             ).save()

    dependencies = [
        ('user_profile', '0006_auto_20190820_0727'),
    ]

    operations = [
        migrations.RunPython(add_users),
    ]
