export const types = {
  AUTH_USER_STARTED: "AUTH_USER_STARTED",
  AUTH_USER_SUCCESS: "AUTH_USER_SUCCESS",
  AUTH_USER_FAILURE: "AUTH_USER_FAILURE",
  UPDATE_USER: "UPDATE_USER",
  LOGIN_FORM: "LOGIN_FORM"
};
