# Generated by Django 2.1 on 2018-08-18 09:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180815_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField(blank=True, max_length=350)),
                ('date_logged', models.DateTimeField()),
                ('given_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback', to='accounts.UserProfile')),
                ('given_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedback', to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IL', 'Inappropriate language'), ('FA', 'Fake account'), ('MS', 'Misuse of service'), ('OT', 'Other')], max_length=2)),
                ('comments', models.TextField(max_length=500)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to='accounts.UserProfile')),
                ('reporting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_report', to='accounts.UserProfile')),
            ],
        ),
    ]
