# Generated by Django 2.1 on 2018-08-18 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_feedback_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_logged',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_logged',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
