# Generated by Django 2.1 on 2018-08-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180818_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='given_by_user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='given_to_user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporting_user',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
