# Generated by Django 2.1 on 2018-08-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180820_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_picture',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
