# Generated by Django 2.1 on 2018-08-29 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180827_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairs', to='accounts.UserProfile'),
        ),
    ]
