class Reading:
    """ Model for reading in a file """
    def __init__(self, *args):
        self.pkt = args[0]
        self.max_temperature_c = args[1]
        self.mean_temperature_c = args[2]
        self.min_temperature_c = args[3]
        self.dew_point_c = args[4]
        self.mean_dew_point_c = args[5]
        self.mean_dew_point_c = args[6]
        self.max_humidity = args[7]
        self.mean_humidity = args[8]
        self.min_humidity = args[9]
        self.max_sealevel_pressure_hpa = args[10]
        self.mean_sealevel_pressure_hpa = args[11]
        self.min_sealevel_pressure_hpa = args[12]
        self.max_visibility_km = args[13]
        self.mean_visibility_km = args[14]
        self.min_visibility_km = args[15]
        self.max_windspeed_kmh = args[16]
        self.mean_windspeed_kmh = args[17]
        self.max_gustspeed_kmh = args[18]
        self.precipitation_mm = args[19]
        self.cloud_cover = args[20]
        self.events = args[21]
        self.wind_dir_degrees = args[22]
