# Generated by Django 2.1.1 on 2018-10-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0002_auto_20181001_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballot',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='updated_at',
            new_name='modified_at',
        ),
    ]
