# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('source_url', models.URLField(unique=True)),
                ('image_url', models.URLField()),
                ('abstract', models.TextField()),
                ('detail', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='NewsPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('source_url', models.URLField(unique=True)),
                ('spider_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'News Paper',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='news_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_news.NewsPaper'),
        ),
    ]
