# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newspaper',
            options={'verbose_name_plural': 'News Paper'},
        ),
        migrations.AlterField(
            model_name='news',
            name='news_url',
            field=models.URLField(unique=True),
        ),
    ]
