# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_news', '0002_auto_20170705_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='website',
            field=models.URLField(unique=True),
        ),
    ]
