# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='image',
            field=models.FileField(default='usig ', upload_to=''),
            preserve_default=False,
        ),
    ]
