# Generated by Django 2.1.5 on 2019-01-19 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trends',
            fields=[
                ('trend_link', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('profile_image', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('tweet_data', models.TextField()),
                ('trend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Trends')),
            ],
        ),
    ]
