# Generated by Django 2.2.4 on 2019-09-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
