# Generated by Django 2.2.4 on 2019-09-12 08:29

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190912_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
    ]
