# Generated by Django 2.2.4 on 2019-09-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopcity', '0001_initial'),
        ('users', '0009_auto_20190912_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sku_id', models.CharField(max_length=50)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='users.Cart')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopcity.Product')),
            ],
        ),
    ]
