# Generated by Django 2.2.4 on 2019-09-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190913_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sku_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
