# Generated by Django 2.2.4 on 2019-09-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190913_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sku_colour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sku_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
