# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170718_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
