# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20170718_0938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateTime',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age_year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
