# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myfacebook', '0006_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date_time',
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
