# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfacebook', '0007_auto_20171030_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='detail',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
