# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfacebook', '0008_auto_20171031_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
