# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 01:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memsapi_app', '0002_auto_20170728_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 1, 37, 49, 247831, tzinfo=utc)),
        ),
    ]
