{"phone": ["\n        \n    "], "title": ["Zenchai"], "speciality": ["Coffee & Tea"], "district": ["\n            Lower East Side        "], "address": ["\n        94 Rivington St", "New York, NY 10002\n    "]}
{"phone": ["\n        (646) 968-4634\n    "], "title": ["&pizza"], "speciality": ["Pizza", "Vegan", "Vegetarian"], "district": ["\n            Flatiron        "], "address": ["\n        15 W 28th St", "New York, NY 10001\n    "]}
{"phone": ["\n        (347) 987-4103\n    "], "title": ["Za-Ya Ramen"], "speciality": ["Ramen", "Soup", "Noodles"], "district": ["\n            Carroll Gardens        "], "address": ["\n        545 Court St", "Brooklyn, NY 11231\n    "]}
{"phone": ["\n        (212) 564-0869\n    "], "title": ["Beyond Sushi Herald Square"], "speciality": ["Vegan", "Sushi Bars", "Vegetarian"], "district": ["\n            Midtown West        "], "address": ["\n        134 West 37th St", "New York, NY 10018\n    "]}
{"phone": ["\n        (718) 857-0222\n    "], "title": ["U-gu"], "speciality": ["Sushi Bars", "Japanese", "Desserts"], "district": ["\n            Clinton Hill        "], "address": ["\n        541 Myrtle Ave", "Brooklyn, NY 11205\n    "]}
{"phone": ["\n        (212) 966-5014\n    "], "title": ["The Pok\u00e9Spot"], "speciality": ["Poke", "Hawaiian", "Salad"], "district": ["\n            Nolita        "], "address": ["\n        25 Cleveland Pl", "New York, NY 10012\n    "]}
{"phone": ["\n        (646) 590-3276\n    "], "title": ["Ramen Ishida"], "speciality": ["Ramen"], "district": ["\n            Lower East Side        "], "address": ["\n        122 Ludlow St", "New York, NY 10002\n    "]}
{"phone": ["\n        (347) 971-7024\n    "], "title": ["The Notorious NY"], "speciality": ["Cocktail Bars", "Lounges", "Venues & Event Spaces"], "district": ["\n            Meatpacking District, West Village        "], "address": ["\n        18 9th Ave", "New York, NY 10014\n    "]}
{"phone": ["\n        (212) 602-9991\n    "], "title": ["Hole in the Wall"], "speciality": ["Breakfast & Brunch", "Cocktail Bars", "Juice Bars & Smoothies"], "district": ["\n            Financial District        "], "address": ["\n        15 Cliff St", "New York, NY 10038\n    "]}
{"phone": ["\n        (646) 883-5453\n    "], "title": ["Jajaja"], "speciality": ["Mexican", "Vegan", "Bars"], "district": ["\n            Lower East Side        "], "address": ["\n        162 E Broadway", "New York, NY 10002\n    "]}
