# Generated by Django 2.2.4 on 2019-08-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
