# Generated by Django 2.2.4 on 2019-08-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190823_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloon',
            name='shop_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
