# Generated by Django 2.2.4 on 2019-09-04 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190904_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Reservation'),
        ),
    ]
