# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170727_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
