class Constants():
    PRODUCT_ID = 'product_id'
    NAME = 'name'
    URL = 'url'
    IMG_URL = 'img_url'
    STYLE_NUMBER = 'style_number'
    BRAND = 'brand'
    DESCRIPTION = 'description'
    CATEGORIES = 'categories'
    FEATURES = 'features'
    SKUS = 'skus'
    SKU_ID = 'sku_id'
    PRICE = 'price'
    COLOR = 'color'
    SIZE = 'size'
    FIT = 'fit'
