# Generated by Django 2.2.6 on 2019-10-28 07:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0005_auto_20191024_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=150)),
                ('thumbnail', models.ImageField(default='default_note_image.png', upload_to='note_book_thumbnails')),
                ('is_public', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynotes.NoteBook')),
            ],
        ),
    ]
