# Generated by Django 2.2.6 on 2019-10-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0006_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='note_book',
        ),
    ]
