# Generated by Django 2.2.6 on 2019-11-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0010_notebook_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='isbn',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
