# Generated by Django 2.2.7 on 2019-11-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0011_auto_20191107_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
