# Generated by Django 2.2.7 on 2019-11-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0012_auto_20191118_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
