# Generated by Django 2.2.7 on 2019-11-27 12:05

from django.db import migrations
from django.utils.text import slugify


def slugify_note_title(apps, schema_editor):
    """ generating slug for all notes in the application """
    note_list = apps.get_model('mynotes', 'note')
    for note in note_list.objects.all():
        note.slug = slugify(note.title)
        note.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0014_auto_20191127_1205'),
    ]

    operations = [
        migrations.RunPython(slugify_note_title)
    ]
