# Generated by Django 2.2.3 on 2019-07-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
