# Generated by Django 2.2.3 on 2019-08-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='timezone_offset',
            field=models.IntegerField(choices=[(0, '0'), (5, '5')], default=5),
        ),
    ]
