# Generated by Django 2.2.3 on 2019-07-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_task_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
