# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.CharField(blank=True, max_length=30, null=True)),
                ('budget', models.IntegerField()),
                ('homepage', models.CharField(blank=True, max_length=50, null=True)),
                ('tmdb_id', models.IntegerField()),
                ('original_language', models.CharField(max_length=15)),
                ('original_title', models.CharField(max_length=50)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.FloatField()),
                ('poster_path', models.CharField(blank=True, max_length=30, null=True)),
                ('release_date', models.DateField()),
                ('revenue', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('status', models.CharField(max_length=15)),
                ('tagline', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(max_length=50)),
                ('video', models.BooleanField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
            ],
        ),
    ]
