# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tag_line',
            field=models.TextField(blank=True, null=True),
        ),
    ]
