# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20170911_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
