# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20170912_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(default=0),
        ),
    ]
