# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20170916_1345'),
    ]

    operations = [
        migrations.RunSQL(
            ('CREATE FULLTEXT INDEX `idx_movies_movie_title` ON `movie_time`.`movies_movie` (title)',),
            ('DROP INDEX `idx_movies_movie_title` ON `movie_time`.`movies_movie`',)
        ),
    ]
