# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20170922_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterIndexTogether(
            name='date',
            index_together=set([('day', 'month', 'year')]),
        ),
    ]
