# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='first name', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='last name', max_length=30),
        ),
    ]
