# Generated by Django 2.1.1 on 2018-09-18 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2018, 9, 18, 10, 44, 10, 154953, tzinfo=utc))),
                ('precipitation', models.FloatField(null=True)),
                ('cloud_cover', models.IntegerField(null=True)),
                ('events', models.CharField(max_length=150, null=True)),
                ('wind_dir_degrees', models.IntegerField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.City')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_value', models.FloatField(null=True)),
                ('mean_value', models.FloatField(null=True)),
                ('min_value', models.FloatField(null=True)),
                ('max_gust_speed', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='weather',
            name='dew_point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='weather.WeatherCharacteristics'),
        ),
        migrations.AddField(
            model_name='weather',
            name='humidity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='weather.WeatherCharacteristics'),
        ),
        migrations.AddField(
            model_name='weather',
            name='sea_pressure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='weather.WeatherCharacteristics'),
        ),
        migrations.AddField(
            model_name='weather',
            name='temperature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='weather.WeatherCharacteristics'),
        ),
        migrations.AddField(
            model_name='weather',
            name='visibility',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='weather.WeatherCharacteristics'),
        ),
        migrations.AddField(
            model_name='weather',
            name='wind',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='weather.WeatherCharacteristics'),
        ),
    ]
