# Generated by Django 2.1.1 on 2018-09-18 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
