# Generated by Django 2.1.1 on 2018-09-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20180918_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathercharacteristics',
            name='max_gust_speed',
        ),
        migrations.AddField(
            model_name='weather',
            name='max_gust_speed',
            field=models.IntegerField(null=True),
        ),
    ]
