# Generated by Django 2.1.1 on 2018-09-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20180919_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='cloud_cover',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='max_gust_speed',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_dir_degrees',
            field=models.SmallIntegerField(null=True),
        ),
    ]
