# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20170704_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='instagram.Post'),
        ),
    ]
