# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20170704_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='user',
            name='followed_by',
            field=models.ManyToManyField(related_name='_user_followed_by_+', to='instagram.User'),
        ),
    ]
