# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20170704_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-pk']},
        ),
    ]
