# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_auto_20170704_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='_user_followed_by_+', to='instagram.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_user_following_+', to='instagram.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(blank=True, to='instagram.Post'),
        ),
    ]
