# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_auto_20170704_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
    ]
