# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0013_auto_20170711_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followed_by',
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, to='instagram.Profile'),
        ),
    ]
