# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_store.Product'),
        ),
        migrations.AlterField(
            model_name='skus',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_store.Product'),
        ),
    ]
