# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_store', '0002_auto_20170717_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_store.Brand'),
        ),
    ]
