# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_store', '0003_auto_20170710_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=50, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
    ]
