# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('super_store', '0005_auto_20170710_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Add Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Update Date'),
        ),
    ]
