# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_store', '0006_auto_20170710_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image_icon',
            field=models.ImageField(upload_to=''),
        ),
    ]
