# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_store', '0007_auto_20170710_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skus',
            name='price',
            field=models.FloatField(),
        ),
    ]
