# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_store', '0011_auto_20170713_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to=settings.AUTH_USER_MODEL),
        ),
    ]
