# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_store', '0012_auto_20170713_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='owner',
        ),
    ]
