# Generated by Django 2.1.2 on 2018-11-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20181112_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='creator',
            new_name='user',
        ),
    ]
