# Generated by Django 2.1.2 on 2018-11-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20181112_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
