# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test',
            field=models.CharField(default='ala bla', max_length=10),
            preserve_default=False,
        ),
    ]
