# Generated by Django 2.2.6 on 2019-11-06 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20191106_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 6, 11, 23, 23, 626559, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Hi', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 6, 11, 23, 23, 626011, tzinfo=utc)),
        ),
    ]
